In [1]:
!pip install pandas google-cloud-bigquery
!pip install pandas-gbq
import pandas as pd

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (1.3.3)
Collecting google-cloud-bigquery
  Using cached google_cloud_bigquery-3.11.4-py2.py3-none-any.whl (219 kB)
Requirement already satisfied: python-dateutil>=2.7.3 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from pandas) (1.23.4)
Requirement already satisfied: pytz>=2017.3 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from pandas) (2021.3)
Collecting google-resumable-media<3.0dev,>=0.6.0
  Using cached google_resumable_media-2.6.0-py2.py3-none-any.whl (80 kB)
Collecting proto-plus<2.0.0dev,>=1.15.0
  Using cached proto_plus-1.22.3-py3-none-any.whl (48 kB)
Requirement already satisfied: requests<3.0.0dev,>=2.21.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from google-cloud-bigquery) (2.28.1)
Collecting google-cloud-core<3.0.0dev,>=1.6.0
  Using cached google_cloud_core-2.3.3-py2.py3-none-any.whl (29 kB)
Collecting protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5
  Using cached protobuf-4.24.2-cp37-abi3-macosx_10_9_universal2.whl (409 kB)
Collecting google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5
  Using cached google_api_core-2.11.1-py3-none-any.whl (120 kB)
Requirement already satisfied: grpcio<2.0dev,>=1.47.0 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from google-cloud-bigquery) (1.50.0)
Requirement already satisfied: packaging>=20.0.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from google-cloud-bigquery) (21.3)
Collecting googleapis-common-protos<2.0.dev0,>=1.56.2
  Using cached googleapis_common_protos-1.60.0-py2.py3-none-any.whl (227 kB)
Collecting google-auth<3.0.dev0,>=2.14.1
  Using cached google_auth-2.22.0-py2.py3-none-any.whl (181 kB)
Collecting grpcio-status<2.0.dev0,>=1.33.2
  Using cached grpcio_status-1.57.0-py3-none-any.whl (5.1 kB)
Collecting google-crc32c<2.0dev,>=1.0
  Downloading google_crc32c-1.5.0-cp38-cp38-macosx_10_9_x86_64.whl (30 kB)
Requirement already satisfied: six>=1.5.2 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from grpcio<2.0dev,>=1.47.0->google-cloud-bigquery) (1.15.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from packaging>=20.0.0->google-cloud-bigquery) (2.4.7)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from requests<3.0.0dev,>=2.21.0->google-cloud-bigquery) (3.3)
Requirement already satisfied: charset-normalizer<3,>=2 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from requests<3.0.0dev,>=2.21.0->google-cloud-bigquery) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from requests<3.0.0dev,>=2.21.0->google-cloud-bigquery) (2020.6.20)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from requests<3.0.0dev,>=2.21.0->google-cloud-bigquery) (1.26.11)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from google-auth<3.0.dev0,>=2.14.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-bigquery) (5.2.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from google-auth<3.0.dev0,>=2.14.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-bigquery) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from google-auth<3.0.dev0,>=2.14.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-bigquery) (4.9)
Collecting grpcio<2.0dev,>=1.47.0
  Downloading grpcio-1.57.0-cp38-cp38-macosx_10_10_universal2.whl (9.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 12.3 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.dev0,>=2.14.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-bigquery) (0.4.8)
Installing collected packages: protobuf, grpcio, google-crc32c, proto-plus, googleapis-common-protos, google-resumable-media, google-auth, grpcio-status, google-api-core, google-cloud-core, google-cloud-bigquery
  Attempting uninstall: grpcio
    Found existing installation: grpcio 1.50.0
    Uninstalling grpcio-1.50.0:
      Successfully uninstalled grpcio-1.50.0
  Attempting uninstall: google-auth
    Found existing installation: google-auth 2.13.0
    Uninstalling google-auth-2.13.0:
      Successfully uninstalled google-auth-2.13.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.10.0 requires protobuf<3.20,>=3.9.2, but you have protobuf 4.24.2 which is incompatible.
tensorboard 2.10.1 requires protobuf<3.20,>=3.9.2, but you have protobuf 4.24.2 which is incompatible.
Successfully installed google-api-core-2.11.1 google-auth-2.22.0 google-cloud-bigquery-3.11.4 google-cloud-core-2.3.3 google-crc32c-1.5.0 google-resumable-media-2.6.0 googleapis-common-protos-1.60.0 grpcio-1.57.0 grpcio-status-1.57.0 proto-plus-1.22.3 protobuf-4.24.2

[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
Defaulting to user installation because normal site-packages is not writeable
Collecting pandas-gbq
  Downloading pandas_gbq-0.19.2-py2.py3-none-any.whl (25 kB)
Requirement already satisfied: numpy>=1.16.6 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from pandas-gbq) (1.23.4)
Collecting google-cloud-bigquery-storage<3.0.0dev,>=2.16.2
  Downloading google_cloud_bigquery_storage-2.22.0-py2.py3-none-any.whl (190 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.9/190.9 kB 5.5 MB/s eta 0:00:00
Requirement already satisfied: google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from pandas-gbq) (3.11.4)
Collecting google-auth-oauthlib>=0.7.0
  Downloading google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: google-auth>=2.13.0 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from pandas-gbq) (2.22.0)
Requirement already satisfied: pandas>=1.1.4 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from pandas-gbq) (1.3.3)
Requirement already satisfied: setuptools in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from pandas-gbq) (67.6.0)
Collecting pydata-google-auth>=1.5.0
  Downloading pydata_google_auth-1.8.2-py2.py3-none-any.whl (15 kB)
Requirement already satisfied: google-api-core<3.0.0dev,>=2.10.2 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from pandas-gbq) (2.11.1)
Collecting pyarrow>=3.0.0
  Downloading pyarrow-13.0.0-cp38-cp38-macosx_10_14_x86_64.whl (25.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.9/25.9 MB 11.5 MB/s eta 0:00:0000:0100:01
Collecting db-dtypes<2.0.0,>=1.0.4
  Downloading db_dtypes-1.1.1-py2.py3-none-any.whl (14 kB)
Requirement already satisfied: packaging>=17.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from db-dtypes<2.0.0,>=1.0.4->pandas-gbq) (21.3)
Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (1.60.0)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0.dev0,>=3.19.5 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (4.24.2)
Requirement already satisfied: requests<3.0.0.dev0,>=2.18.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (2.28.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from google-auth>=2.13.0->pandas-gbq) (0.2.8)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from google-auth>=2.13.0->pandas-gbq) (5.2.0)
Requirement already satisfied: six>=1.9.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from google-auth>=2.13.0->pandas-gbq) (1.15.0)
Requirement already satisfied: urllib3<2.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from google-auth>=2.13.0->pandas-gbq) (1.26.11)
Requirement already satisfied: rsa<5,>=3.1.4 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from google-auth>=2.13.0->pandas-gbq) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from google-auth-oauthlib>=0.7.0->pandas-gbq) (1.3.1)
Requirement already satisfied: google-resumable-media<3.0dev,>=0.6.0 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5->pandas-gbq) (2.6.0)
Requirement already satisfied: grpcio<2.0dev,>=1.47.0 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5->pandas-gbq) (1.57.0)
Requirement already satisfied: google-cloud-core<3.0.0dev,>=1.6.0 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5->pandas-gbq) (2.3.3)
Requirement already satisfied: python-dateutil<3.0dev,>=2.7.2 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5->pandas-gbq) (2.8.2)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.15.0 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5->pandas-gbq) (1.22.3)
Requirement already satisfied: pytz>=2017.3 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from pandas>=1.1.4->pandas-gbq) (2021.3)
Requirement already satisfied: grpcio-status<2.0.dev0,>=1.33.2 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (1.57.0)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from google-resumable-media<3.0dev,>=0.6.0->google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5->pandas-gbq) (1.5.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from packaging>=17.0->db-dtypes<2.0.0,>=1.0.4->pandas-gbq) (2.4.7)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from pyasn1-modules>=0.2.1->google-auth>=2.13.0->pandas-gbq) (0.4.8)
Requirement already satisfied: charset-normalizer<3,>=2 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (2.1.0)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (2020.6.20)
Requirement already satisfied: oauthlib>=3.0.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.7.0->pandas-gbq) (3.2.1)
Installing collected packages: pyarrow, google-auth-oauthlib, db-dtypes, pydata-google-auth, google-cloud-bigquery-storage, pandas-gbq
  Attempting uninstall: google-auth-oauthlib
    Found existing installation: google-auth-oauthlib 0.4.6
    Uninstalling google-auth-oauthlib-0.4.6:
      Successfully uninstalled google-auth-oauthlib-0.4.6
  WARNING: The script google-oauthlib-tool is installed in '/Users/ellvin/Library/Python/3.8/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorboard 2.10.1 requires google-auth-oauthlib<0.5,>=0.4.1, but you have google-auth-oauthlib 1.0.0 which is incompatible.
tensorboard 2.10.1 requires protobuf<3.20,>=3.9.2, but you have protobuf 4.24.2 which is incompatible.
Successfully installed db-dtypes-1.1.1 google-auth-oauthlib-1.0.0 google-cloud-bigquery-storage-2.22.0 pandas-gbq-0.19.2 pyarrow-13.0.0 pydata-google-auth-1.8.2

[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: pip install --upgrade pip

In [3]:
pip install pandas-gbq

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Collecting pandas-gbq
  Using cached pandas_gbq-0.19.2-py2.py3-none-any.whl (25 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.9/site-packages (from pandas-gbq) (68.1.2)
Collecting db-dtypes<2.0.0,>=1.0.4 (from pandas-gbq)
  Using cached db_dtypes-1.1.1-py2.py3-none-any.whl (14 kB)
Requirement already satisfied: numpy>=1.16.6 in /usr/local/lib/python3.9/site-packages (from pandas-gbq) (1.25.2)
Requirement already satisfied: pandas>=1.1.4 in /usr/local/lib/python3.9/site-packages (from pandas-gbq) (2.1.0)
Collecting pyarrow>=3.0.0 (from pandas-gbq)
  Obtaining dependency information for pyarrow>=3.0.0 from https://files.pythonhosted.org/packages/00/92/fb70afe5f5e0c78c8d920f556bc126b591e7253ecd5b6406f92f3e0f25f1/pyarrow-13.0.0-cp39-cp39-macosx_10_14_x86_64.whl.metadata
  Downloading pyarrow-13.0.0-cp39-cp39-macosx_10_14_x86_64.whl.metadata (3.0 kB)
Collecting pydata-google-auth>=1.5.0 (from pandas-gbq)
  Obtaining dependency information for pydata-google-auth>=1.5.0 from https://files.pythonhosted.org/packages/28/6b/3320c9ddbfc572108917e8432a07e8bd1e40054d94b5ad40c755afdc1160/pydata_google_auth-1.8.2-py2.py3-none-any.whl.metadata
  Downloading pydata_google_auth-1.8.2-py2.py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: google-api-core<3.0.0dev,>=2.10.2 in /usr/local/lib/python3.9/site-packages (from pandas-gbq) (2.11.1)
Requirement already satisfied: google-auth>=2.13.0 in /usr/local/lib/python3.9/site-packages (from pandas-gbq) (2.22.0)
Collecting google-auth-oauthlib>=0.7.0 (from pandas-gbq)
  Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5 in /usr/local/lib/python3.9/site-packages (from pandas-gbq) (3.11.4)
Collecting google-cloud-bigquery-storage<3.0.0dev,>=2.16.2 (from pandas-gbq)
  Obtaining dependency information for google-cloud-bigquery-storage<3.0.0dev,>=2.16.2 from https://files.pythonhosted.org/packages/83/eb/e5016412a9c6ac26b46480f83d58112b99b48c0e38ae040b46f8795dea6f/google_cloud_bigquery_storage-2.22.0-py2.py3-none-any.whl.metadata
  Downloading google_cloud_bigquery_storage-2.22.0-py2.py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: packaging>=17.0 in /Users/ellvin/Library/Python/3.9/lib/python/site-packages (from db-dtypes<2.0.0,>=1.0.4->pandas-gbq) (23.1)
Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in /usr/local/lib/python3.9/site-packages (from google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (1.60.0)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0.dev0,>=3.19.5 in /usr/local/lib/python3.9/site-packages (from google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (4.24.2)
Requirement already satisfied: requests<3.0.0.dev0,>=2.18.0 in /usr/local/lib/python3.9/site-packages (from google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (2.31.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.9/site-packages (from google-auth>=2.13.0->pandas-gbq) (5.3.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.9/site-packages (from google-auth>=2.13.0->pandas-gbq) (0.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.9/site-packages (from google-auth>=2.13.0->pandas-gbq) (4.9)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.9/site-packages (from google-auth>=2.13.0->pandas-gbq) (1.16.0)
Requirement already satisfied: urllib3<2.0 in /usr/local/lib/python3.9/site-packages (from google-auth>=2.13.0->pandas-gbq) (1.26.16)
Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib>=0.7.0->pandas-gbq)
  Using cached requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: grpcio<2.0dev,>=1.47.0 in /usr/local/lib/python3.9/site-packages (from google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5->pandas-gbq) (1.57.0)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.15.0 in /usr/local/lib/python3.9/site-packages (from google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5->pandas-gbq) (1.22.3)
Requirement already satisfied: google-cloud-core<3.0.0dev,>=1.6.0 in /usr/local/lib/python3.9/site-packages (from google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5->pandas-gbq) (2.3.3)
Requirement already satisfied: google-resumable-media<3.0dev,>=0.6.0 in /usr/local/lib/python3.9/site-packages (from google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5->pandas-gbq) (2.6.0)
Requirement already satisfied: python-dateutil<3.0dev,>=2.7.2 in /Users/ellvin/Library/Python/3.9/lib/python/site-packages (from google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5->pandas-gbq) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.9/site-packages (from pandas>=1.1.4->pandas-gbq) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.9/site-packages (from pandas>=1.1.4->pandas-gbq) (2023.3)
Requirement already satisfied: grpcio-status<2.0.dev0,>=1.33.2 in /usr/local/lib/python3.9/site-packages (from google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (1.57.0)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /usr/local/lib/python3.9/site-packages (from google-resumable-media<3.0dev,>=0.6.0->google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5->pandas-gbq) (1.5.0)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /usr/local/lib/python3.9/site-packages (from pyasn1-modules>=0.2.1->google-auth>=2.13.0->pandas-gbq) (0.5.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.9/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (2023.7.22)
Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.7.0->pandas-gbq)
  Using cached oauthlib-3.2.2-py3-none-any.whl (151 kB)
Using cached google_cloud_bigquery_storage-2.22.0-py2.py3-none-any.whl (190 kB)
Downloading pyarrow-13.0.0-cp39-cp39-macosx_10_14_x86_64.whl (25.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.9/25.9 MB 8.5 MB/s eta 0:00:0000:0100:01m
Using cached pydata_google_auth-1.8.2-py2.py3-none-any.whl (15 kB)
Installing collected packages: pyarrow, oauthlib, requests-oauthlib, google-auth-oauthlib, db-dtypes, pydata-google-auth, google-cloud-bigquery-storage, pandas-gbq
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Successfully installed db-dtypes-1.1.1 google-auth-oauthlib-1.0.0 google-cloud-bigquery-storage-2.22.0 oauthlib-3.2.2 pandas-gbq-0.19.2 pyarrow-13.0.0 pydata-google-auth-1.8.2 requests-oauthlib-1.3.1
Note: you may need to restart the kernel to use updated packages.

In [93]:
from google.oauth2 import service_account
import pandas as pd
import pandas_gbq as gbq
credentials_path = 'token.json'

# Authenticate with your credentials
credentials = service_account.Credentials.from_service_account_file(
    credentials_path, scopes=['https://www.googleapis.com/auth/bigquery'])

# Set the credentials for pandas_gbq
gbq.context.credentials = credentials

In [94]:
project_id = 'capstone-398012'
dataset_id = 'capstone'
table_id = "X_Y_merged"

In [95]:
from pandas_gbq import read_gbq

query = f"""
SELECT *
FROM `{project_id}.{dataset_id}.{table_id}`

"""

# Authenticate and read data from BigQuery into a DataFrame
df = read_gbq(query, project_id=project_id, dialect='standard')
df

/usr/local/lib/python3.9/site-packages/google/cloud/bigquery/table.py:2155: UserWarning: A progress bar was requested, but there was an error loading the tqdm library. Please install tqdm to use the progress bar functionality.
  record_batch = self.to_arrow(

,CompNo,yyyy,mm,StkIndx,STInt,dtdlevel,dtdtrend,liqnonfinlevel,liqnonfintrend,ni2talevel,...,sigma,liqfinlevel,lqfintrend,DTDmedianFin,DTDmedianNonFin,dummy297fin,EventDate,Event_type,Sector_Number,Exchange
0,26990,2023,7,0.110445,0.009928,4.874043,0.537756,0.000000,0.000000e+00,0.003009,...,0.049103,-3.418569,-0.149087,2.596495,0.000000,1,202307,0,14.0,15
1,27005,2023,7,0.110445,0.009928,6.375460,-0.447124,0.000000,0.000000e+00,0.003226,...,0.065213,-1.643673,0.291813,2.596495,0.000000,1,202307,0,15.0,15
2,27030,2023,7,0.110445,0.009928,3.875769,0.519613,0.000000,0.000000e+00,0.002722,...,0.060196,-1.765111,0.115349,2.596495,0.000000,1,202307,0,14.0,15
3,27035,2023,7,0.110445,0.009928,2.130511,0.361442,0.000000,0.000000e+00,0.000949,...,0.064415,-3.602947,0.037359,2.596495,0.000000,1,202307,0,14.0,15
4,27037,2023,7,0.110445,0.009928,5.436649,-3.216218,0.000000,0.000000e+00,-0.002387,...,0.170656,-0.816766,0.010185,2.596495,0.000000,1,202307,0,14.0,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8617,211542,2023,7,0.015960,-0.010290,NaN,NaN,1.595832,-2.220446e-16,-0.094074,...,NaN,0.000000,0.000000,0.000000,2.087496,0,202307,0,18.0,16
8618,211546,2023,7,0.015960,-0.010290,7.349152,-0.538347,2.291604,0.000000e+00,-0.088621,...,0.225663,0.000000,0.000000,0.000000,2.087496,0,202307,0,19.0,16
8619,211564,2023,7,0.015960,-0.010290,0.972123,0.000000,4.787727,0.000000e+00,-0.055728,...,NaN,0.000000,0.000000,0.000000,2.087496,0,202307,0,18.0,16
8620,211664,2023,7,0.015960,-0.010290,4.090032,0.000000,1.198122,0.000000e+00,-0.074286,...,0.333307,0.000000,0.000000,0.000000,2.087496,0,202307,0,18.0,16
8621,211787,2023,7,0.015960,-0.010290,NaN,NaN,2.318369,0.000000e+00,-0.048236,...,NaN,0.000000,0.000000,0.000000,2.087496,0,202307,0,18.0,16

In [96]:
df.isna().sum().sort_values(ascending=False)

dtdlevel           2297
dtdtrend           2297
m2b                2229
sigma              2144
ni2talevel         2135
ni2tatrend         2135
liqnonfinlevel     1737
liqnonfintrend     1737
lqfintrend          431
liqfinlevel         431
sizelevel           156
sizetrend           156
Sector_Number       114
DTDmedianNonFin       2
DTDmedianFin          1
dummy297fin           0
EventDate             0
Event_type            0
CompNo                0
yyyy                  0
STInt                 0
StkIndx               0
mm                    0
Exchange              0
dtype: int64

In [97]:
new_df = df
new_df

,CompNo,yyyy,mm,StkIndx,STInt,dtdlevel,dtdtrend,liqnonfinlevel,liqnonfintrend,ni2talevel,...,sigma,liqfinlevel,lqfintrend,DTDmedianFin,DTDmedianNonFin,dummy297fin,EventDate,Event_type,Sector_Number,Exchange
0,26990,2023,7,0.110445,0.009928,4.874043,0.537756,0.000000,0.000000e+00,0.003009,...,0.049103,-3.418569,-0.149087,2.596495,0.000000,1,202307,0,14.0,15
1,27005,2023,7,0.110445,0.009928,6.375460,-0.447124,0.000000,0.000000e+00,0.003226,...,0.065213,-1.643673,0.291813,2.596495,0.000000,1,202307,0,15.0,15
2,27030,2023,7,0.110445,0.009928,3.875769,0.519613,0.000000,0.000000e+00,0.002722,...,0.060196,-1.765111,0.115349,2.596495,0.000000,1,202307,0,14.0,15
3,27035,2023,7,0.110445,0.009928,2.130511,0.361442,0.000000,0.000000e+00,0.000949,...,0.064415,-3.602947,0.037359,2.596495,0.000000,1,202307,0,14.0,15
4,27037,2023,7,0.110445,0.009928,5.436649,-3.216218,0.000000,0.000000e+00,-0.002387,...,0.170656,-0.816766,0.010185,2.596495,0.000000,1,202307,0,14.0,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8617,211542,2023,7,0.015960,-0.010290,NaN,NaN,1.595832,-2.220446e-16,-0.094074,...,NaN,0.000000,0.000000,0.000000,2.087496,0,202307,0,18.0,16
8618,211546,2023,7,0.015960,-0.010290,7.349152,-0.538347,2.291604,0.000000e+00,-0.088621,...,0.225663,0.000000,0.000000,0.000000,2.087496,0,202307,0,19.0,16
8619,211564,2023,7,0.015960,-0.010290,0.972123,0.000000,4.787727,0.000000e+00,-0.055728,...,NaN,0.000000,0.000000,0.000000,2.087496,0,202307,0,18.0,16
8620,211664,2023,7,0.015960,-0.010290,4.090032,0.000000,1.198122,0.000000e+00,-0.074286,...,0.333307,0.000000,0.000000,0.000000,2.087496,0,202307,0,18.0,16
8621,211787,2023,7,0.015960,-0.010290,NaN,NaN,2.318369,0.000000e+00,-0.048236,...,NaN,0.000000,0.000000,0.000000,2.087496,0,202307,0,18.0,16

In [98]:
nan_count = new_df.isna().sum(axis=1)

# Create a new column with the NaN count
new_df['nan_count'] = nan_count
new_df

,CompNo,yyyy,mm,StkIndx,STInt,dtdlevel,dtdtrend,liqnonfinlevel,liqnonfintrend,ni2talevel,...,liqfinlevel,lqfintrend,DTDmedianFin,DTDmedianNonFin,dummy297fin,EventDate,Event_type,Sector_Number,Exchange,nan_count
0,26990,2023,7,0.110445,0.009928,4.874043,0.537756,0.000000,0.000000e+00,0.003009,...,-3.418569,-0.149087,2.596495,0.000000,1,202307,0,14.0,15,0
1,27005,2023,7,0.110445,0.009928,6.375460,-0.447124,0.000000,0.000000e+00,0.003226,...,-1.643673,0.291813,2.596495,0.000000,1,202307,0,15.0,15,0
2,27030,2023,7,0.110445,0.009928,3.875769,0.519613,0.000000,0.000000e+00,0.002722,...,-1.765111,0.115349,2.596495,0.000000,1,202307,0,14.0,15,0
3,27035,2023,7,0.110445,0.009928,2.130511,0.361442,0.000000,0.000000e+00,0.000949,...,-3.602947,0.037359,2.596495,0.000000,1,202307,0,14.0,15,0
4,27037,2023,7,0.110445,0.009928,5.436649,-3.216218,0.000000,0.000000e+00,-0.002387,...,-0.816766,0.010185,2.596495,0.000000,1,202307,0,14.0,15,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8617,211542,2023,7,0.015960,-0.010290,NaN,NaN,1.595832,-2.220446e-16,-0.094074,...,0.000000,0.000000,0.000000,2.087496,0,202307,0,18.0,16,3
8618,211546,2023,7,0.015960,-0.010290,7.349152,-0.538347,2.291604,0.000000e+00,-0.088621,...,0.000000,0.000000,0.000000,2.087496,0,202307,0,19.0,16,0
8619,211564,2023,7,0.015960,-0.010290,0.972123,0.000000,4.787727,0.000000e+00,-0.055728,...,0.000000,0.000000,0.000000,2.087496,0,202307,0,18.0,16,1
8620,211664,2023,7,0.015960,-0.010290,4.090032,0.000000,1.198122,0.000000e+00,-0.074286,...,0.000000,0.000000,0.000000,2.087496,0,202307,0,18.0,16,0
8621,211787,2023,7,0.015960,-0.010290,NaN,NaN,2.318369,0.000000e+00,-0.048236,...,0.000000,0.000000,0.000000,2.087496,0,202307,0,18.0,16,6

In [99]:
#list of columns that contain NA 
na_cols = ['liqnonfinlevel', 'liqnonfintrend', 'dtdlevel', 'dtdtrend', 'DTDmedianNonFin', 'Sector_Number', 'DTDmedianFin', 'sigma', 'm2b', 'ni2talevel', 'ni2tatrend', 'lqfintrend', 'liqfinlevel', 'sizelevel', 'sizetrend']

#create new columns (_notNA) for each column that contains na values where 1 if original column is not na and 0 otherwise
for col in na_cols:
    new_col = col + '_notNA'
    new_df[new_col] = new_df[col].notna().astype(int)

new_df

,CompNo,yyyy,mm,StkIndx,STInt,dtdlevel,dtdtrend,liqnonfinlevel,liqnonfintrend,ni2talevel,...,Sector_Number_notNA,DTDmedianFin_notNA,sigma_notNA,m2b_notNA,ni2talevel_notNA,ni2tatrend_notNA,lqfintrend_notNA,liqfinlevel_notNA,sizelevel_notNA,sizetrend_notNA
0,26990,2023,7,0.110445,0.009928,4.874043,0.537756,0.000000,0.000000e+00,0.003009,...,1,1,1,1,1,1,1,1,1,1
1,27005,2023,7,0.110445,0.009928,6.375460,-0.447124,0.000000,0.000000e+00,0.003226,...,1,1,1,1,1,1,1,1,1,1
2,27030,2023,7,0.110445,0.009928,3.875769,0.519613,0.000000,0.000000e+00,0.002722,...,1,1,1,1,1,1,1,1,1,1
3,27035,2023,7,0.110445,0.009928,2.130511,0.361442,0.000000,0.000000e+00,0.000949,...,1,1,1,1,1,1,1,1,1,1
4,27037,2023,7,0.110445,0.009928,5.436649,-3.216218,0.000000,0.000000e+00,-0.002387,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8617,211542,2023,7,0.015960,-0.010290,NaN,NaN,1.595832,-2.220446e-16,-0.094074,...,1,1,0,1,1,1,1,1,1,1
8618,211546,2023,7,0.015960,-0.010290,7.349152,-0.538347,2.291604,0.000000e+00,-0.088621,...,1,1,1,1,1,1,1,1,1,1
8619,211564,2023,7,0.015960,-0.010290,0.972123,0.000000,4.787727,0.000000e+00,-0.055728,...,1,1,0,1,1,1,1,1,1,1
8620,211664,2023,7,0.015960,-0.010290,4.090032,0.000000,1.198122,0.000000e+00,-0.074286,...,1,1,1,1,1,1,1,1,1,1
8621,211787,2023,7,0.015960,-0.010290,NaN,NaN,2.318369,0.000000e+00,-0.048236,...,1,1,0,0,1,1,1,1,0,0

In [100]:
grouped_df = new_df.groupby('CompNo')
grouped_df[na_cols].mean()

,liqnonfinlevel,liqnonfintrend,dtdlevel,dtdtrend,DTDmedianNonFin,Sector_Number,DTDmedianFin,sigma,m2b,ni2talevel,ni2tatrend,lqfintrend,liqfinlevel,sizelevel,sizetrend
CompNo,,,,,,,,,,,,,,,
7998,0.000000,0.000000,NaN,NaN,0.000000,14.0,3.453191,NaN,NaN,NaN,NaN,NaN,NaN,-4.230614,-0.402998
18729,0.401776,-0.213851,0.857282,-0.050431,3.244875,17.0,0.000000,0.176984,0.522089,0.021992,-0.023712,0.0,0.0,1.488217,-0.184953
22043,1.561046,-0.163734,0.415476,-0.342681,3.244875,16.0,0.000000,0.502508,0.309116,-0.069377,-0.047603,0.0,0.0,-4.629652,-0.464887
26978,1.135380,0.003565,5.726758,0.733746,3.619887,17.0,0.000000,0.069988,1.121369,0.004543,-0.000324,0.0,0.0,0.716143,0.053630
26979,0.566073,-0.048648,9.589458,1.250903,3.861603,16.0,0.000000,0.051762,2.270983,0.006294,-0.000341,0.0,0.0,5.268695,0.063211
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212228,NaN,NaN,NaN,NaN,3.244875,19.0,0.000000,NaN,NaN,NaN,NaN,0.0,0.0,-2.809265,0.000000
212229,NaN,NaN,NaN,NaN,3.244875,10.0,0.000000,NaN,NaN,NaN,NaN,0.0,0.0,-2.435643,0.000000
212230,NaN,NaN,NaN,NaN,3.244875,19.0,0.000000,NaN,NaN,NaN,NaN,0.0,0.0,-3.153829,0.000000
212250,NaN,NaN,NaN,NaN,3.244875,17.0,0.000000,NaN,NaN,NaN,NaN,0.0,0.0,-3.600412,0.000000
212251,NaN,NaN,NaN,NaN,3.244875,17.0,0.000000,NaN,NaN,NaN,NaN,0.0,0.0,-1.235374,0.000000

In [101]:
mean_values = grouped_df[na_cols].transform('mean')

new_df[na_cols] = new_df[na_cols].fillna(mean_values)

new_df

,CompNo,yyyy,mm,StkIndx,STInt,dtdlevel,dtdtrend,liqnonfinlevel,liqnonfintrend,ni2talevel,...,Sector_Number_notNA,DTDmedianFin_notNA,sigma_notNA,m2b_notNA,ni2talevel_notNA,ni2tatrend_notNA,lqfintrend_notNA,liqfinlevel_notNA,sizelevel_notNA,sizetrend_notNA
0,26990,2023,7,0.110445,0.009928,4.874043,0.537756,0.000000,0.000000e+00,0.003009,...,1,1,1,1,1,1,1,1,1,1
1,27005,2023,7,0.110445,0.009928,6.375460,-0.447124,0.000000,0.000000e+00,0.003226,...,1,1,1,1,1,1,1,1,1,1
2,27030,2023,7,0.110445,0.009928,3.875769,0.519613,0.000000,0.000000e+00,0.002722,...,1,1,1,1,1,1,1,1,1,1
3,27035,2023,7,0.110445,0.009928,2.130511,0.361442,0.000000,0.000000e+00,0.000949,...,1,1,1,1,1,1,1,1,1,1
4,27037,2023,7,0.110445,0.009928,5.436649,-3.216218,0.000000,0.000000e+00,-0.002387,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8617,211542,2023,7,0.015960,-0.010290,NaN,NaN,1.595832,-2.220446e-16,-0.094074,...,1,1,0,1,1,1,1,1,1,1
8618,211546,2023,7,0.015960,-0.010290,7.349152,-0.538347,2.291604,0.000000e+00,-0.088621,...,1,1,1,1,1,1,1,1,1,1
8619,211564,2023,7,0.015960,-0.010290,0.972123,0.000000,4.787727,0.000000e+00,-0.055728,...,1,1,0,1,1,1,1,1,1,1
8620,211664,2023,7,0.015960,-0.010290,4.090032,0.000000,1.198122,0.000000e+00,-0.074286,...,1,1,1,1,1,1,1,1,1,1
8621,211787,2023,7,0.015960,-0.010290,NaN,NaN,2.318369,0.000000e+00,-0.048236,...,1,1,0,0,1,1,1,1,0,0

In [102]:
print(new_df[new_df.isna().any(axis=1)])

      CompNo  yyyy mm   StkIndx     STInt    dtdlevel   dtdtrend  \
127    30643  2023  7  0.110445  0.009928         NaN        NaN
290    36114  2023  7  0.110445  0.009928   16.785337   9.127457
448    44088  2023  7  0.110445  0.009928         NaN        NaN
600   131867  2023  7  0.110445  0.009928    0.675758  -0.475205
886   205354  2023  7  0.110445  0.009928  103.738407 -35.341088
...      ...   ... ..       ...       ...         ...        ...
8611  211423  2023  7  0.015960 -0.010290   12.160022   0.000000
8613  211434  2023  7  0.015960 -0.010290         NaN        NaN
8617  211542  2023  7  0.015960 -0.010290         NaN        NaN
8619  211564  2023  7  0.015960 -0.010290    0.972123   0.000000
8621  211787  2023  7  0.015960 -0.010290         NaN        NaN

      liqnonfinlevel  liqnonfintrend  ni2talevel  ...  Sector_Number_notNA  \
127         0.000000    0.000000e+00   -0.000004  ...                    1
290         0.000000    0.000000e+00    0.011002  ...                    1
448         0.000000    0.000000e+00   -0.000651  ...                    1
600         0.000000    0.000000e+00   -0.101552  ...                    1
886         0.000000    0.000000e+00    0.000951  ...                    1
...              ...             ...         ...  ...                  ...
8611        3.903415    4.440892e-16   -0.043879  ...                    1
8613        1.103168    0.000000e+00   -0.104520  ...                    1
8617        1.595832   -2.220446e-16   -0.094074  ...                    1
8619        4.787727    0.000000e+00   -0.055728  ...                    1
8621        2.318369    0.000000e+00   -0.048236  ...                    1

      DTDmedianFin_notNA  sigma_notNA  m2b_notNA  ni2talevel_notNA  \
127                    1            1          1                 1
290                    1            1          1                 1
448                    1            1          1                 1
600                    1            1          1                 1
886                    1            1          1                 1
...                  ...          ...        ...               ...
8611                   1            0          1                 1
8613                   1            0          1                 1
8617                   1            0          1                 1
8619                   1            0          1                 1
8621                   1            0          0                 1

      ni2tatrend_notNA  lqfintrend_notNA  liqfinlevel_notNA  sizelevel_notNA  \
127                  1                 1                  1                1
290                  1                 0                  0                1
448                  1                 1                  1                1
600                  1                 0                  0                1
886                  1                 0                  0                1
...                ...               ...                ...              ...
8611                 1                 1                  1                1
8613                 1                 1                  1                1
8617                 1                 1                  1                1
8619                 1                 1                  1                1
8621                 1                 1                  1                0

      sizetrend_notNA
127                 1
290                 1
448                 1
600                 1
886                 1
...               ...
8611                1
8613                1
8617                1
8619                1
8621                0

[1951 rows x 40 columns]

In [103]:
new_df.isna().sum().sort_values(ascending=False)

dtdlevel                 1674
dtdtrend                 1674
m2b                      1603
sigma                    1509
ni2talevel               1509
ni2tatrend               1509
liqnonfinlevel           1293
liqnonfintrend           1293
liqfinlevel               251
lqfintrend                251
sizelevel                 145
sizetrend                 145
Sector_Number             114
DTDmedianNonFin             2
DTDmedianFin                1
sigma_notNA                 0
DTDmedianFin_notNA          0
ni2talevel_notNA            0
Sector_Number_notNA         0
m2b_notNA                   0
CompNo                      0
ni2tatrend_notNA            0
dtdtrend_notNA              0
lqfintrend_notNA            0
liqfinlevel_notNA           0
sizelevel_notNA             0
DTDmedianNonFin_notNA       0
EventDate                   0
dtdlevel_notNA              0
liqnonfintrend_notNA        0
liqnonfinlevel_notNA        0
nan_count                   0
Exchange                    0
Event_type                  0
yyyy                        0
dummy297fin                 0
STInt                       0
StkIndx                     0
mm                          0
sizetrend_notNA             0
dtype: int64

In [104]:
test_df = df.dropna()
test_df

,CompNo,yyyy,mm,StkIndx,STInt,dtdlevel,dtdtrend,liqnonfinlevel,liqnonfintrend,ni2talevel,...,Sector_Number_notNA,DTDmedianFin_notNA,sigma_notNA,m2b_notNA,ni2talevel_notNA,ni2tatrend_notNA,lqfintrend_notNA,liqfinlevel_notNA,sizelevel_notNA,sizetrend_notNA
0,26990,2023,7,0.110445,0.009928,4.874043,0.537756,0.000000,0.0,0.003009,...,1,1,1,1,1,1,1,1,1,1
1,27005,2023,7,0.110445,0.009928,6.375460,-0.447124,0.000000,0.0,0.003226,...,1,1,1,1,1,1,1,1,1,1
2,27030,2023,7,0.110445,0.009928,3.875769,0.519613,0.000000,0.0,0.002722,...,1,1,1,1,1,1,1,1,1,1
3,27035,2023,7,0.110445,0.009928,2.130511,0.361442,0.000000,0.0,0.000949,...,1,1,1,1,1,1,1,1,1,1
4,27037,2023,7,0.110445,0.009928,5.436649,-3.216218,0.000000,0.0,-0.002387,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8614,211440,2023,7,0.015960,-0.010290,5.584671,-0.041361,1.763750,0.0,0.046797,...,1,1,1,1,1,1,1,1,1,1
8615,211478,2023,7,0.015960,-0.010290,1.693796,-0.200789,2.121717,0.0,-0.044299,...,1,1,1,1,1,1,1,1,1,1
8616,211494,2023,7,0.015960,-0.010290,13.575741,0.258830,2.108105,0.0,-0.003608,...,1,1,1,1,1,1,1,1,1,1
8618,211546,2023,7,0.015960,-0.010290,7.349152,-0.538347,2.291604,0.0,-0.088621,...,1,1,1,1,1,1,1,1,1,1
8620,211664,2023,7,0.015960,-0.010290,4.090032,0.000000,1.198122,0.0,-0.074286,...,1,1,1,1,1,1,1,1,1,1

In [106]:
test_df['Event_type'] = test_df['Event_type'].map(lambda x : 0 if x ==2  else x)

/var/folders/rz/d40gjr2505ddk3wl3mnzmvdm0000gn/T/ipykernel_22722/2314109866.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df['Event_type'] = test_df['Event_type'].map(lambda x : 0 if x ==2  else x)

In [107]:
test_df['Event_type'].value_counts()

Event_type
0    6596
1      75
Name: count, dtype: int64

In [90]:
test_df.to_gbq(destination_table=f'{project_id}.{dataset_id}.filled_table', project_id=project_id, if_exists='replace')