In [1]:
!pip install pandas google-cloud-bigquery
!pip install pandas-gbq
import pandas as pd

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (1.3.3)
Collecting google-cloud-bigquery
  Using cached google_cloud_bigquery-3.11.4-py2.py3-none-any.whl (219 kB)
Requirement already satisfied: python-dateutil>=2.7.3 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from pandas) (1.23.4)
Requirement already satisfied: pytz>=2017.3 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from pandas) (2021.3)
Collecting google-resumable-media<3.0dev,>=0.6.0
  Using cached google_resumable_media-2.6.0-py2.py3-none-any.whl (80 kB)
Collecting proto-plus<2.0.0dev,>=1.15.0
  Using cached proto_plus-1.22.3-py3-none-any.whl (48 kB)
Requirement already satisfied: requests<3.0.0dev,>=2.21.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from google-cloud-bigquery) (2.28.1)
Collecting google-cloud-core<3.0.0dev,>=1.6.0
  Using cached google_cloud_core-2.3.3-py2.py3-none-any.whl (29 kB)
Collecting protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5
  Using cached protobuf-4.24.2-cp37-abi3-macosx_10_9_universal2.whl (409 kB)
Collecting google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5
  Using cached google_api_core-2.11.1-py3-none-any.whl (120 kB)
Requirement already satisfied: grpcio<2.0dev,>=1.47.0 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from google-cloud-bigquery) (1.50.0)
Requirement already satisfied: packaging>=20.0.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from google-cloud-bigquery) (21.3)
Collecting googleapis-common-protos<2.0.dev0,>=1.56.2
  Using cached googleapis_common_protos-1.60.0-py2.py3-none-any.whl (227 kB)
Collecting google-auth<3.0.dev0,>=2.14.1
  Using cached google_auth-2.22.0-py2.py3-none-any.whl (181 kB)
Collecting grpcio-status<2.0.dev0,>=1.33.2
  Using cached grpcio_status-1.57.0-py3-none-any.whl (5.1 kB)
Collecting google-crc32c<2.0dev,>=1.0
  Downloading google_crc32c-1.5.0-cp38-cp38-macosx_10_9_x86_64.whl (30 kB)
Requirement already satisfied: six>=1.5.2 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from grpcio<2.0dev,>=1.47.0->google-cloud-bigquery) (1.15.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from packaging>=20.0.0->google-cloud-bigquery) (2.4.7)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from requests<3.0.0dev,>=2.21.0->google-cloud-bigquery) (3.3)
Requirement already satisfied: charset-normalizer<3,>=2 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from requests<3.0.0dev,>=2.21.0->google-cloud-bigquery) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from requests<3.0.0dev,>=2.21.0->google-cloud-bigquery) (2020.6.20)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from requests<3.0.0dev,>=2.21.0->google-cloud-bigquery) (1.26.11)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from google-auth<3.0.dev0,>=2.14.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-bigquery) (5.2.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from google-auth<3.0.dev0,>=2.14.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-bigquery) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from google-auth<3.0.dev0,>=2.14.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-bigquery) (4.9)
Collecting grpcio<2.0dev,>=1.47.0
  Downloading grpcio-1.57.0-cp38-cp38-macosx_10_10_universal2.whl (9.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 12.3 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.dev0,>=2.14.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-bigquery) (0.4.8)
Installing collected packages: protobuf, grpcio, google-crc32c, proto-plus, googleapis-common-protos, google-resumable-media, google-auth, grpcio-status, google-api-core, google-cloud-core, google-cloud-bigquery
  Attempting uninstall: grpcio
    Found existing installation: grpcio 1.50.0
    Uninstalling grpcio-1.50.0:
      Successfully uninstalled grpcio-1.50.0
  Attempting uninstall: google-auth
    Found existing installation: google-auth 2.13.0
    Uninstalling google-auth-2.13.0:
      Successfully uninstalled google-auth-2.13.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.10.0 requires protobuf<3.20,>=3.9.2, but you have protobuf 4.24.2 which is incompatible.
tensorboard 2.10.1 requires protobuf<3.20,>=3.9.2, but you have protobuf 4.24.2 which is incompatible.
Successfully installed google-api-core-2.11.1 google-auth-2.22.0 google-cloud-bigquery-3.11.4 google-cloud-core-2.3.3 google-crc32c-1.5.0 google-resumable-media-2.6.0 googleapis-common-protos-1.60.0 grpcio-1.57.0 grpcio-status-1.57.0 proto-plus-1.22.3 protobuf-4.24.2

[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
Defaulting to user installation because normal site-packages is not writeable
Collecting pandas-gbq
  Downloading pandas_gbq-0.19.2-py2.py3-none-any.whl (25 kB)
Requirement already satisfied: numpy>=1.16.6 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from pandas-gbq) (1.23.4)
Collecting google-cloud-bigquery-storage<3.0.0dev,>=2.16.2
  Downloading google_cloud_bigquery_storage-2.22.0-py2.py3-none-any.whl (190 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.9/190.9 kB 5.5 MB/s eta 0:00:00
Requirement already satisfied: google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from pandas-gbq) (3.11.4)
Collecting google-auth-oauthlib>=0.7.0
  Downloading google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: google-auth>=2.13.0 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from pandas-gbq) (2.22.0)
Requirement already satisfied: pandas>=1.1.4 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from pandas-gbq) (1.3.3)
Requirement already satisfied: setuptools in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from pandas-gbq) (67.6.0)
Collecting pydata-google-auth>=1.5.0
  Downloading pydata_google_auth-1.8.2-py2.py3-none-any.whl (15 kB)
Requirement already satisfied: google-api-core<3.0.0dev,>=2.10.2 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from pandas-gbq) (2.11.1)
Collecting pyarrow>=3.0.0
  Downloading pyarrow-13.0.0-cp38-cp38-macosx_10_14_x86_64.whl (25.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.9/25.9 MB 11.5 MB/s eta 0:00:0000:0100:01
Collecting db-dtypes<2.0.0,>=1.0.4
  Downloading db_dtypes-1.1.1-py2.py3-none-any.whl (14 kB)
Requirement already satisfied: packaging>=17.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from db-dtypes<2.0.0,>=1.0.4->pandas-gbq) (21.3)
Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (1.60.0)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0.dev0,>=3.19.5 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (4.24.2)
Requirement already satisfied: requests<3.0.0.dev0,>=2.18.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (2.28.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from google-auth>=2.13.0->pandas-gbq) (0.2.8)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from google-auth>=2.13.0->pandas-gbq) (5.2.0)
Requirement already satisfied: six>=1.9.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from google-auth>=2.13.0->pandas-gbq) (1.15.0)
Requirement already satisfied: urllib3<2.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from google-auth>=2.13.0->pandas-gbq) (1.26.11)
Requirement already satisfied: rsa<5,>=3.1.4 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from google-auth>=2.13.0->pandas-gbq) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from google-auth-oauthlib>=0.7.0->pandas-gbq) (1.3.1)
Requirement already satisfied: google-resumable-media<3.0dev,>=0.6.0 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5->pandas-gbq) (2.6.0)
Requirement already satisfied: grpcio<2.0dev,>=1.47.0 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5->pandas-gbq) (1.57.0)
Requirement already satisfied: google-cloud-core<3.0.0dev,>=1.6.0 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5->pandas-gbq) (2.3.3)
Requirement already satisfied: python-dateutil<3.0dev,>=2.7.2 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5->pandas-gbq) (2.8.2)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.15.0 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5->pandas-gbq) (1.22.3)
Requirement already satisfied: pytz>=2017.3 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from pandas>=1.1.4->pandas-gbq) (2021.3)
Requirement already satisfied: grpcio-status<2.0.dev0,>=1.33.2 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (1.57.0)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from google-resumable-media<3.0dev,>=0.6.0->google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5->pandas-gbq) (1.5.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from packaging>=17.0->db-dtypes<2.0.0,>=1.0.4->pandas-gbq) (2.4.7)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /Users/ellvin/Library/Python/3.8/lib/python/site-packages (from pyasn1-modules>=0.2.1->google-auth>=2.13.0->pandas-gbq) (0.4.8)
Requirement already satisfied: charset-normalizer<3,>=2 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (2.1.0)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (2020.6.20)
Requirement already satisfied: oauthlib>=3.0.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.7.0->pandas-gbq) (3.2.1)
Installing collected packages: pyarrow, google-auth-oauthlib, db-dtypes, pydata-google-auth, google-cloud-bigquery-storage, pandas-gbq
  Attempting uninstall: google-auth-oauthlib
    Found existing installation: google-auth-oauthlib 0.4.6
    Uninstalling google-auth-oauthlib-0.4.6:
      Successfully uninstalled google-auth-oauthlib-0.4.6
  WARNING: The script google-oauthlib-tool is installed in '/Users/ellvin/Library/Python/3.8/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorboard 2.10.1 requires google-auth-oauthlib<0.5,>=0.4.1, but you have google-auth-oauthlib 1.0.0 which is incompatible.
tensorboard 2.10.1 requires protobuf<3.20,>=3.9.2, but you have protobuf 4.24.2 which is incompatible.
Successfully installed db-dtypes-1.1.1 google-auth-oauthlib-1.0.0 google-cloud-bigquery-storage-2.22.0 pandas-gbq-0.19.2 pyarrow-13.0.0 pydata-google-auth-1.8.2

[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: pip install --upgrade pip

In [3]:
pip install pandas-gbq

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Collecting pandas-gbq
  Using cached pandas_gbq-0.19.2-py2.py3-none-any.whl (25 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.9/site-packages (from pandas-gbq) (68.1.2)
Collecting db-dtypes<2.0.0,>=1.0.4 (from pandas-gbq)
  Using cached db_dtypes-1.1.1-py2.py3-none-any.whl (14 kB)
Requirement already satisfied: numpy>=1.16.6 in /usr/local/lib/python3.9/site-packages (from pandas-gbq) (1.25.2)
Requirement already satisfied: pandas>=1.1.4 in /usr/local/lib/python3.9/site-packages (from pandas-gbq) (2.1.0)
Collecting pyarrow>=3.0.0 (from pandas-gbq)
  Obtaining dependency information for pyarrow>=3.0.0 from https://files.pythonhosted.org/packages/00/92/fb70afe5f5e0c78c8d920f556bc126b591e7253ecd5b6406f92f3e0f25f1/pyarrow-13.0.0-cp39-cp39-macosx_10_14_x86_64.whl.metadata
  Downloading pyarrow-13.0.0-cp39-cp39-macosx_10_14_x86_64.whl.metadata (3.0 kB)
Collecting pydata-google-auth>=1.5.0 (from pandas-gbq)
  Obtaining dependency information for pydata-google-auth>=1.5.0 from https://files.pythonhosted.org/packages/28/6b/3320c9ddbfc572108917e8432a07e8bd1e40054d94b5ad40c755afdc1160/pydata_google_auth-1.8.2-py2.py3-none-any.whl.metadata
  Downloading pydata_google_auth-1.8.2-py2.py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: google-api-core<3.0.0dev,>=2.10.2 in /usr/local/lib/python3.9/site-packages (from pandas-gbq) (2.11.1)
Requirement already satisfied: google-auth>=2.13.0 in /usr/local/lib/python3.9/site-packages (from pandas-gbq) (2.22.0)
Collecting google-auth-oauthlib>=0.7.0 (from pandas-gbq)
  Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5 in /usr/local/lib/python3.9/site-packages (from pandas-gbq) (3.11.4)
Collecting google-cloud-bigquery-storage<3.0.0dev,>=2.16.2 (from pandas-gbq)
  Obtaining dependency information for google-cloud-bigquery-storage<3.0.0dev,>=2.16.2 from https://files.pythonhosted.org/packages/83/eb/e5016412a9c6ac26b46480f83d58112b99b48c0e38ae040b46f8795dea6f/google_cloud_bigquery_storage-2.22.0-py2.py3-none-any.whl.metadata
  Downloading google_cloud_bigquery_storage-2.22.0-py2.py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: packaging>=17.0 in /Users/ellvin/Library/Python/3.9/lib/python/site-packages (from db-dtypes<2.0.0,>=1.0.4->pandas-gbq) (23.1)
Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in /usr/local/lib/python3.9/site-packages (from google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (1.60.0)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0.dev0,>=3.19.5 in /usr/local/lib/python3.9/site-packages (from google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (4.24.2)
Requirement already satisfied: requests<3.0.0.dev0,>=2.18.0 in /usr/local/lib/python3.9/site-packages (from google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (2.31.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.9/site-packages (from google-auth>=2.13.0->pandas-gbq) (5.3.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.9/site-packages (from google-auth>=2.13.0->pandas-gbq) (0.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.9/site-packages (from google-auth>=2.13.0->pandas-gbq) (4.9)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.9/site-packages (from google-auth>=2.13.0->pandas-gbq) (1.16.0)
Requirement already satisfied: urllib3<2.0 in /usr/local/lib/python3.9/site-packages (from google-auth>=2.13.0->pandas-gbq) (1.26.16)
Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib>=0.7.0->pandas-gbq)
  Using cached requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: grpcio<2.0dev,>=1.47.0 in /usr/local/lib/python3.9/site-packages (from google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5->pandas-gbq) (1.57.0)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.15.0 in /usr/local/lib/python3.9/site-packages (from google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5->pandas-gbq) (1.22.3)
Requirement already satisfied: google-cloud-core<3.0.0dev,>=1.6.0 in /usr/local/lib/python3.9/site-packages (from google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5->pandas-gbq) (2.3.3)
Requirement already satisfied: google-resumable-media<3.0dev,>=0.6.0 in /usr/local/lib/python3.9/site-packages (from google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5->pandas-gbq) (2.6.0)
Requirement already satisfied: python-dateutil<3.0dev,>=2.7.2 in /Users/ellvin/Library/Python/3.9/lib/python/site-packages (from google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5->pandas-gbq) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.9/site-packages (from pandas>=1.1.4->pandas-gbq) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.9/site-packages (from pandas>=1.1.4->pandas-gbq) (2023.3)
Requirement already satisfied: grpcio-status<2.0.dev0,>=1.33.2 in /usr/local/lib/python3.9/site-packages (from google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (1.57.0)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /usr/local/lib/python3.9/site-packages (from google-resumable-media<3.0dev,>=0.6.0->google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5->pandas-gbq) (1.5.0)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /usr/local/lib/python3.9/site-packages (from pyasn1-modules>=0.2.1->google-auth>=2.13.0->pandas-gbq) (0.5.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.9/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (2023.7.22)
Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.7.0->pandas-gbq)
  Using cached oauthlib-3.2.2-py3-none-any.whl (151 kB)
Using cached google_cloud_bigquery_storage-2.22.0-py2.py3-none-any.whl (190 kB)
Downloading pyarrow-13.0.0-cp39-cp39-macosx_10_14_x86_64.whl (25.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.9/25.9 MB 8.5 MB/s eta 0:00:0000:0100:01m
Using cached pydata_google_auth-1.8.2-py2.py3-none-any.whl (15 kB)
Installing collected packages: pyarrow, oauthlib, requests-oauthlib, google-auth-oauthlib, db-dtypes, pydata-google-auth, google-cloud-bigquery-storage, pandas-gbq
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Successfully installed db-dtypes-1.1.1 google-auth-oauthlib-1.0.0 google-cloud-bigquery-storage-2.22.0 oauthlib-3.2.2 pandas-gbq-0.19.2 pyarrow-13.0.0 pydata-google-auth-1.8.2 requests-oauthlib-1.3.1
Note: you may need to restart the kernel to use updated packages.

In [109]:
from google.oauth2 import service_account
import pandas as pd
import pandas_gbq as gbq
credentials_path = 'token.json'

# Authenticate with your credentials
credentials = service_account.Credentials.from_service_account_file(
    credentials_path, scopes=['https://www.googleapis.com/auth/bigquery'])

# Set the credentials for pandas_gbq
gbq.context.credentials = credentials

In [110]:
project_id = 'capstone-398012'
dataset_id = 'capstone'
table_id = "X_Y_merged"

In [112]:
from pandas_gbq import read_gbq

query = f"""
SELECT *
FROM `{project_id}.{dataset_id}.{table_id}`

"""

# Authenticate and read data from BigQuery into a DataFrame
df = read_gbq(query, project_id=project_id, dialect='standard')
df

,CompNo,yyyy,mm,StkIndx,STInt,dtdlevel,dtdtrend,liqnonfinlevel,liqnonfintrend,ni2talevel,...,sigma,liqfinlevel,lqfintrend,DTDmedianFin,DTDmedianNonFin,dummy297fin,EventDate,Event_type,Sector_Number,Exchange
0,26995,1988,1,NaN,0.011518,NaN,NaN,NaN,NaN,NaN,...,NaN,0.000000,0.000000,0.000000,NaN,0,198801,0,NaN,<NA>
1,27002,1988,1,NaN,0.011518,NaN,NaN,NaN,NaN,NaN,...,NaN,0.000000,0.000000,0.000000,NaN,0,198801,0,NaN,<NA>
2,27016,1988,1,NaN,0.011518,NaN,NaN,NaN,NaN,NaN,...,NaN,0.000000,0.000000,0.000000,NaN,0,198801,0,NaN,<NA>
3,27024,1988,1,NaN,0.011518,NaN,NaN,NaN,NaN,NaN,...,NaN,0.000000,0.000000,0.000000,NaN,0,198801,0,NaN,<NA>
4,27029,1988,1,NaN,0.011518,NaN,NaN,NaN,NaN,NaN,...,NaN,0.000000,0.000000,0.000000,NaN,0,198801,0,NaN,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2753075,200171,2022,12,-0.144284,-0.010290,4.672422,-0.945082,0.0,0.0,0.010130,...,0.063727,-6.513012,0.324092,3.352699,0.0,1,None,0,NaN,<NA>
2753076,205823,2022,12,-0.144284,-0.010290,9.769421,0.217952,0.0,0.0,-0.003547,...,NaN,-6.837600,1.011353,3.352699,0.0,1,None,0,NaN,<NA>
2753077,206386,2022,12,-0.144284,-0.010290,1.170952,-1.000180,0.0,0.0,-0.062454,...,0.553841,-3.610828,-1.017549,3.352699,0.0,1,None,0,NaN,<NA>
2753078,206506,2022,12,-0.144284,-0.010290,4.466948,0.000000,0.0,0.0,-0.035020,...,0.164950,-0.768627,0.000000,3.352699,0.0,1,None,0,NaN,<NA>
2753079,207519,2022,12,-0.144284,-0.010290,1.964562,-1.357927,0.0,0.0,-0.009489,...,0.719142,-3.432906,-3.436180,3.352699,0.0,1,None,0,NaN,<NA>

In [113]:
df.isna().sum().sort_values(ascending=False)

Sector_Number      2744572
Exchange           2744458
EventDate           680533
dtdlevel            415714
dtdtrend            415714
liqnonfinlevel      313474
liqnonfintrend      313474
m2b                 304272
ni2talevel          295769
ni2tatrend          295769
sigma               289740
sizetrend           160735
sizelevel           160735
DTDmedianNonFin     126687
liqfinlevel          64819
lqfintrend           64819
StkIndx              47043
DTDmedianFin         29918
STInt                17318
yyyy                     0
dummy297fin              0
Event_type               0
mm                       0
CompNo                   0
dtype: int64

In [136]:
new_df = df
new_df

,CompNo,yyyy,mm,StkIndx,STInt,dtdlevel,dtdtrend,liqnonfinlevel,liqnonfintrend,ni2talevel,...,ni2tatrend_notNA,sigma_notNA,sizetrend_notNA,sizelevel_notNA,DTDmedianNonFin_notNA,liqfinlevel_notNA,lqfintrend_notNA,StkIndx_notNA,DTDmedianFin_notNA,STInt_notNA
0,26995,1988,1,0.099507,0.011518,3.357402,-0.007521,0.267996,0.004653,0.003024,...,1,1,1,1,1,1,1,1,1,1
1,27002,1988,1,0.084382,0.011518,7.332251,0.147392,0.805760,0.006890,0.006706,...,1,1,1,1,1,1,1,1,1,1
2,27016,1988,1,0.093809,0.011518,7.184027,0.078564,0.299215,-0.000388,0.005005,...,1,1,1,1,1,1,1,1,1,1
3,27024,1988,1,0.102844,0.011518,3.663156,-0.128699,0.474106,-0.034071,0.000870,...,1,1,1,1,1,1,1,1,1,1
4,27029,1988,1,0.093809,0.011518,7.383713,-0.062306,-0.308982,-0.006267,0.002402,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2753075,200171,2022,12,-0.144284,-0.010290,4.672422,-0.945082,0.000000,0.000000,0.010130,...,1,1,1,1,1,1,1,1,1,1
2753076,205823,2022,12,-0.144284,-0.010290,9.769421,0.217952,0.000000,0.000000,-0.003547,...,1,0,1,1,1,1,1,1,1,1
2753077,206386,2022,12,-0.144284,-0.010290,1.170952,-1.000180,0.000000,0.000000,-0.062454,...,1,1,1,1,1,1,1,1,1,1
2753078,206506,2022,12,-0.144284,-0.010290,4.466948,0.000000,0.000000,0.000000,-0.035020,...,1,1,1,1,1,1,1,1,1,1
2753079,207519,2022,12,-0.144284,-0.010290,1.964562,-1.357927,0.000000,0.000000,-0.009489,...,1,1,1,1,1,1,1,1,1,1

In [137]:
nan_count = new_df.isna().sum(axis=1)

# Create a new column with the NaN count
new_df['nan_count'] = nan_count
new_df

,CompNo,yyyy,mm,StkIndx,STInt,dtdlevel,dtdtrend,liqnonfinlevel,liqnonfintrend,ni2talevel,...,ni2tatrend_notNA,sigma_notNA,sizetrend_notNA,sizelevel_notNA,DTDmedianNonFin_notNA,liqfinlevel_notNA,lqfintrend_notNA,StkIndx_notNA,DTDmedianFin_notNA,STInt_notNA
0,26995,1988,1,0.099507,0.011518,3.357402,-0.007521,0.267996,0.004653,0.003024,...,1,1,1,1,1,1,1,1,1,1
1,27002,1988,1,0.084382,0.011518,7.332251,0.147392,0.805760,0.006890,0.006706,...,1,1,1,1,1,1,1,1,1,1
2,27016,1988,1,0.093809,0.011518,7.184027,0.078564,0.299215,-0.000388,0.005005,...,1,1,1,1,1,1,1,1,1,1
3,27024,1988,1,0.102844,0.011518,3.663156,-0.128699,0.474106,-0.034071,0.000870,...,1,1,1,1,1,1,1,1,1,1
4,27029,1988,1,0.093809,0.011518,7.383713,-0.062306,-0.308982,-0.006267,0.002402,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2753075,200171,2022,12,-0.144284,-0.010290,4.672422,-0.945082,0.000000,0.000000,0.010130,...,1,1,1,1,1,1,1,1,1,1
2753076,205823,2022,12,-0.144284,-0.010290,9.769421,0.217952,0.000000,0.000000,-0.003547,...,1,0,1,1,1,1,1,1,1,1
2753077,206386,2022,12,-0.144284,-0.010290,1.170952,-1.000180,0.000000,0.000000,-0.062454,...,1,1,1,1,1,1,1,1,1,1
2753078,206506,2022,12,-0.144284,-0.010290,4.466948,0.000000,0.000000,0.000000,-0.035020,...,1,1,1,1,1,1,1,1,1,1
2753079,207519,2022,12,-0.144284,-0.010290,1.964562,-1.357927,0.000000,0.000000,-0.009489,...,1,1,1,1,1,1,1,1,1,1

In [138]:
new_df = new_df.drop(['Sector_Number', 'Exchange', 'EventDate'], axis=1)

In [139]:
#list of columns that contain NA 
#na_cols = ['liqnonfinlevel', 'liqnonfintrend', 'dtdlevel', 'dtdtrend', 'DTDmedianNonFin', 'Sector_Number', 'DTDmedianFin', 'sigma', 'm2b', 'ni2talevel', 'ni2tatrend', 'lqfintrend', 'liqfinlevel', 'sizelevel', 'sizetrend']
na_cols = ['dtdlevel', 'dtdtrend', 'liqnonfinlevel', 'liqnonfintrend', 'm2b', 'ni2talevel', 'ni2tatrend', 'sigma', 'sizetrend', 'sizelevel', 'DTDmedianNonFin', 'liqfinlevel', 'lqfintrend', 'StkIndx', 'DTDmedianFin', 'STInt']

#create new columns (_notNA) for each column that contains na values where 1 if original column is not na and 0 otherwise
for col in na_cols:
    new_col = col + '_notNA'
    new_df[new_col] = new_df[col].notna().astype(int)

new_df

,CompNo,yyyy,mm,StkIndx,STInt,dtdlevel,dtdtrend,liqnonfinlevel,liqnonfintrend,ni2talevel,...,ni2tatrend_notNA,sigma_notNA,sizetrend_notNA,sizelevel_notNA,DTDmedianNonFin_notNA,liqfinlevel_notNA,lqfintrend_notNA,StkIndx_notNA,DTDmedianFin_notNA,STInt_notNA
0,26995,1988,1,0.099507,0.011518,3.357402,-0.007521,0.267996,0.004653,0.003024,...,1,1,1,1,1,1,1,1,1,1
1,27002,1988,1,0.084382,0.011518,7.332251,0.147392,0.805760,0.006890,0.006706,...,1,1,1,1,1,1,1,1,1,1
2,27016,1988,1,0.093809,0.011518,7.184027,0.078564,0.299215,-0.000388,0.005005,...,1,1,1,1,1,1,1,1,1,1
3,27024,1988,1,0.102844,0.011518,3.663156,-0.128699,0.474106,-0.034071,0.000870,...,1,1,1,1,1,1,1,1,1,1
4,27029,1988,1,0.093809,0.011518,7.383713,-0.062306,-0.308982,-0.006267,0.002402,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2753075,200171,2022,12,-0.144284,-0.010290,4.672422,-0.945082,0.000000,0.000000,0.010130,...,1,1,1,1,1,1,1,1,1,1
2753076,205823,2022,12,-0.144284,-0.010290,9.769421,0.217952,0.000000,0.000000,-0.003547,...,1,0,1,1,1,1,1,1,1,1
2753077,206386,2022,12,-0.144284,-0.010290,1.170952,-1.000180,0.000000,0.000000,-0.062454,...,1,1,1,1,1,1,1,1,1,1
2753078,206506,2022,12,-0.144284,-0.010290,4.466948,0.000000,0.000000,0.000000,-0.035020,...,1,1,1,1,1,1,1,1,1,1
2753079,207519,2022,12,-0.144284,-0.010290,1.964562,-1.357927,0.000000,0.000000,-0.009489,...,1,1,1,1,1,1,1,1,1,1

In [140]:
grouped_df = new_df.groupby('CompNo')
grouped_df[na_cols].mean()

,dtdlevel,dtdtrend,liqnonfinlevel,liqnonfintrend,m2b,ni2talevel,ni2tatrend,sigma,sizetrend,sizelevel,DTDmedianNonFin,liqfinlevel,lqfintrend,StkIndx,DTDmedianFin,STInt
CompNo,,,,,,,,,,,,,,,,
7998,1.518742,-0.078443,0.000000,0.000000,3.563797,-0.071054,0.002666,0.445451,0.000013,-3.436716,0.000000,-1.177138,-0.075122,0.075529,3.218673,0.002178
14547,-0.539548,0.092665,-0.287932,0.144621,1.276910,-0.057850,-0.013431,0.388691,-0.003109,-2.559309,3.129606,0.000000,0.000000,0.075976,0.000000,0.000509
15984,4.196356,-0.059368,0.532569,0.019535,4.062024,0.004011,-0.000140,0.191686,0.008170,1.203744,3.467877,0.000000,0.000000,0.031920,0.000000,0.001374
18729,1.715101,-0.298528,0.362961,0.010744,0.822375,0.046946,-0.007464,0.192799,0.028287,1.732840,3.203602,0.000000,0.000000,0.111549,0.000000,-0.003699
20131,3.005580,-0.246693,1.624963,-0.188731,1.884004,-0.027036,0.001960,0.297691,-0.035856,-1.546829,3.605205,0.000000,0.000000,0.098629,0.000000,-0.004676
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212228,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,-2.809265,3.244875,0.000000,0.000000,0.110445,0.000000,0.009928
212229,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,-2.435643,3.244875,0.000000,0.000000,0.110445,0.000000,0.009928
212230,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,-3.153829,3.244875,0.000000,0.000000,0.110445,0.000000,0.009928
212250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,-3.600412,3.244875,0.000000,0.000000,0.110445,0.000000,0.009928
212251,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,-1.235374,3.244875,0.000000,0.000000,0.110445,0.000000,0.009928

In [141]:
mean_values = grouped_df[na_cols].transform('mean')

new_df[na_cols] = new_df[na_cols].fillna(mean_values)

new_df

,CompNo,yyyy,mm,StkIndx,STInt,dtdlevel,dtdtrend,liqnonfinlevel,liqnonfintrend,ni2talevel,...,ni2tatrend_notNA,sigma_notNA,sizetrend_notNA,sizelevel_notNA,DTDmedianNonFin_notNA,liqfinlevel_notNA,lqfintrend_notNA,StkIndx_notNA,DTDmedianFin_notNA,STInt_notNA
0,26995,1988,1,0.099507,0.011518,3.357402,-0.007521,0.267996,0.004653,0.003024,...,1,1,1,1,1,1,1,1,1,1
1,27002,1988,1,0.084382,0.011518,7.332251,0.147392,0.805760,0.006890,0.006706,...,1,1,1,1,1,1,1,1,1,1
2,27016,1988,1,0.093809,0.011518,7.184027,0.078564,0.299215,-0.000388,0.005005,...,1,1,1,1,1,1,1,1,1,1
3,27024,1988,1,0.102844,0.011518,3.663156,-0.128699,0.474106,-0.034071,0.000870,...,1,1,1,1,1,1,1,1,1,1
4,27029,1988,1,0.093809,0.011518,7.383713,-0.062306,-0.308982,-0.006267,0.002402,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2753075,200171,2022,12,-0.144284,-0.010290,4.672422,-0.945082,0.000000,0.000000,0.010130,...,1,1,1,1,1,1,1,1,1,1
2753076,205823,2022,12,-0.144284,-0.010290,9.769421,0.217952,0.000000,0.000000,-0.003547,...,1,0,1,1,1,1,1,1,1,1
2753077,206386,2022,12,-0.144284,-0.010290,1.170952,-1.000180,0.000000,0.000000,-0.062454,...,1,1,1,1,1,1,1,1,1,1
2753078,206506,2022,12,-0.144284,-0.010290,4.466948,0.000000,0.000000,0.000000,-0.035020,...,1,1,1,1,1,1,1,1,1,1
2753079,207519,2022,12,-0.144284,-0.010290,1.964562,-1.357927,0.000000,0.000000,-0.009489,...,1,1,1,1,1,1,1,1,1,1

In [142]:
print(new_df[new_df.isna().any(axis=1)])

         CompNo  yyyy  mm   StkIndx     STInt   dtdlevel  dtdtrend  \
131       29105  1988   1  0.118547  0.011518   0.015233 -0.205658
220       31185  1988   1  0.097273  0.011518  -0.317918  0.018524
259       32244  1988   1  0.120716  0.011518   4.481273 -0.159918
289      125741  1988   1  0.118275  0.011518   3.085696  0.260733
331      126960  1988   1  0.118547  0.011518   3.046538  0.335364
...         ...   ...  ..       ...       ...        ...       ...
2753044  210013  2022  12 -0.196544  0.005723        NaN       NaN
2753046  210231  2022  12 -0.196544  0.005723        NaN       NaN
2753047  210264  2022  12 -0.196544  0.005723        NaN       NaN
2753049  210480  2022  12 -0.196544  0.005723  18.182976 -5.515725
2753076  205823  2022  12 -0.144284 -0.010290   9.769421  0.217952

         liqnonfinlevel  liqnonfintrend  ni2talevel  ...  ni2tatrend_notNA  \
131                 NaN             NaN   -0.003016  ...                 1
220                 NaN             NaN   -0.008634  ...                 1
259                 NaN             NaN    0.001164  ...                 1
289                 NaN             NaN    0.006843  ...                 1
331                 NaN             NaN    0.000208  ...                 1
...                 ...             ...         ...  ...               ...
2753044             0.0             0.0    0.000334  ...                 1
2753046             0.0             0.0    0.000924  ...                 1
2753047             0.0             0.0         NaN  ...                 0
2753049             0.0             0.0   -0.000031  ...                 1
2753076             0.0             0.0   -0.003547  ...                 1

         sigma_notNA  sizetrend_notNA  sizelevel_notNA  DTDmedianNonFin_notNA  \
131                1                1                1                      1
220                1                1                1                      1
259                1                1                1                      1
289                1                1                1                      1
331                1                1                1                      1
...              ...              ...              ...                    ...
2753044            0                1                1                      1
2753046            0                1                1                      1
2753047            1                1                1                      1
2753049            0                1                1                      1
2753076            0                1                1                      1

         liqfinlevel_notNA  lqfintrend_notNA  StkIndx_notNA  \
131                      1                 1              1
220                      1                 1              1
259                      1                 1              1
289                      1                 1              1
331                      1                 1              1
...                    ...               ...            ...
2753044                  1                 1              1
2753046                  1                 1              1
2753047                  0                 0              1
2753049                  1                 1              1
2753076                  1                 1              1

         DTDmedianFin_notNA  STInt_notNA
131                       1            1
220                       1            1
259                       1            1
289                       1            1
331                       1            1
...                     ...          ...
2753044                   1            1
2753046                   1            1
2753047                   1            1
2753049                   1            1
2753076                   1            1

[139278 rows x 41 columns]

In [143]:
new_df.isna().sum().sort_values(ascending=False)

liqnonfinlevel           112430
liqnonfintrend           112430
dtdlevel                  93974
dtdtrend                  93974
ni2tatrend                87930
ni2talevel                87930
m2b                       87573
sigma                     73260
sizelevel                 51013
sizetrend                 51013
liqfinlevel               14350
lqfintrend                14350
DTDmedianNonFin             853
DTDmedianFin                 70
StkIndx                      38
ni2tatrend_notNA              0
DTDmedianNonFin_notNA         0
ni2talevel_notNA              0
sigma_notNA                   0
sizetrend_notNA               0
sizelevel_notNA               0
CompNo                        0
liqfinlevel_notNA             0
lqfintrend_notNA              0
liqnonfintrend_notNA          0
StkIndx_notNA                 0
DTDmedianFin_notNA            0
m2b_notNA                     0
Event_type                    0
liqnonfinlevel_notNA          0
dtdtrend_notNA                0
dtdlevel_notNA                0
EventDate_notNA               0
Exchange_notNA                0
Sector_Number_notNA           0
nan_count                     0
yyyy                          0
dummy297fin                   0
STInt                         0
mm                            0
STInt_notNA                   0
dtype: int64

In [144]:
test_df = new_df.dropna()
test_df

,CompNo,yyyy,mm,StkIndx,STInt,dtdlevel,dtdtrend,liqnonfinlevel,liqnonfintrend,ni2talevel,...,ni2tatrend_notNA,sigma_notNA,sizetrend_notNA,sizelevel_notNA,DTDmedianNonFin_notNA,liqfinlevel_notNA,lqfintrend_notNA,StkIndx_notNA,DTDmedianFin_notNA,STInt_notNA
0,26995,1988,1,0.099507,0.011518,3.357402,-0.007521,0.267996,0.004653,0.003024,...,1,1,1,1,1,1,1,1,1,1
1,27002,1988,1,0.084382,0.011518,7.332251,0.147392,0.805760,0.006890,0.006706,...,1,1,1,1,1,1,1,1,1,1
2,27016,1988,1,0.093809,0.011518,7.184027,0.078564,0.299215,-0.000388,0.005005,...,1,1,1,1,1,1,1,1,1,1
3,27024,1988,1,0.102844,0.011518,3.663156,-0.128699,0.474106,-0.034071,0.000870,...,1,1,1,1,1,1,1,1,1,1
4,27029,1988,1,0.093809,0.011518,7.383713,-0.062306,-0.308982,-0.006267,0.002402,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2753074,198755,2022,12,-0.144284,-0.010290,1.100901,-1.240564,0.000000,0.000000,-0.002431,...,1,1,1,1,1,1,1,1,1,1
2753075,200171,2022,12,-0.144284,-0.010290,4.672422,-0.945082,0.000000,0.000000,0.010130,...,1,1,1,1,1,1,1,1,1,1
2753077,206386,2022,12,-0.144284,-0.010290,1.170952,-1.000180,0.000000,0.000000,-0.062454,...,1,1,1,1,1,1,1,1,1,1
2753078,206506,2022,12,-0.144284,-0.010290,4.466948,0.000000,0.000000,0.000000,-0.035020,...,1,1,1,1,1,1,1,1,1,1
2753079,207519,2022,12,-0.144284,-0.010290,1.964562,-1.357927,0.000000,0.000000,-0.009489,...,1,1,1,1,1,1,1,1,1,1

In [145]:
test_df['Event_type'] = test_df['Event_type'].map(lambda x : 0 if x ==2  else x)

/var/folders/rz/d40gjr2505ddk3wl3mnzmvdm0000gn/T/ipykernel_22722/2314109866.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df['Event_type'] = test_df['Event_type'].map(lambda x : 0 if x ==2  else x)

In [146]:
test_df['Event_type'].value_counts()

Event_type
0    2613352
1        450
Name: count, dtype: int64

In [149]:
test_df.isna().sum().sum()

0

In [150]:
test_df.to_gbq(destination_table=f'{project_id}.{dataset_id}.filled_table_2', project_id=project_id, if_exists='replace')