In [22]:
import pandas as pd
import datetime

In [4]:
y_pred_6 = pd.read_csv('y_pred_6.csv')
y_pred_12 = pd.read_csv('y_pred.csv')
y_pred_24 = pd.read_csv('y_pred_24.csv')

In [33]:
print(y_pred_6.shape)
print(y_pred_12.shape)
print(y_pred_24.shape)

(36537, 1)
(36537, 1)
(36537, 1)

In [34]:
y_pred_12

       12 months
0            0.0
1            0.0
2            0.0
3            0.0
4            0.0
...          ...
36532        0.0
36533        0.0
36534        0.0
36535        0.0
36536        0.0

[36537 rows x 1 columns]

In [25]:
result = pd.read_pickle("../../data_preprocessing/cri_compustat_merged_v8.pkl")
date2022 = datetime.datetime(2022, 1, 1)
test_df = result[result["EventDate"] >= date2022]
test_df

,CompNo,year,month,StkIndx,STInt,dtdlevel,dtdtrend,liqnonfinlevel,liqnonfintrend,ni2talevel,...,day_sales_outstanding,working_capital_turnover,price_to_earnings,dividend_payout_ratio,retention_ratio,gross_margin_ratio,operating_profit_margin,ebitda_margin,debt_service_coverage_ratio,interest_coverage_ratio
1142877,51206,2022.0,1,0.222340,-0.010290,4.018672,0.031058,-0.711290,0.119370,-0.002135,...,0.000000,-1.638486,-70.434783,-0.782609,1.782609,69.263293,28.368265,74.409240,0.009588,1.298707
1142878,35555,2022.0,1,0.200978,-0.010836,6.235341,0.642900,-1.009857,0.093713,0.002416,...,52.366027,-1.914551,244.083333,1.160000,-0.160000,33.471354,-33.057292,-20.038221,-0.041869,3.659991
1142879,31384,2022.0,1,0.200978,-0.010836,6.544177,1.221037,0.612863,-0.094203,0.019053,...,255.978284,0.952252,54.696517,0.373134,0.626866,61.470992,-7.386664,-3.180809,-0.041417,17.541667
1142880,39720,2022.0,1,0.200978,-0.010836,4.336223,-0.747313,1.702805,0.493360,0.035574,...,204.524163,0.315086,135.476190,0.000000,1.000000,43.822453,-12.355093,-9.151717,-0.014889,17.403939
1142881,30384,2022.0,1,0.200978,-0.010836,11.258779,2.061880,0.237242,-0.104751,0.011787,...,0.000000,13.218253,159.600000,0.445455,0.554545,49.242253,-19.988957,-10.469728,-0.312583,45.648561
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1179409,27334,2023.0,7,0.110445,0.009928,4.813408,1.285527,-0.311802,0.041775,0.008093,...,220.175780,1.263753,42.117647,0.122549,0.877451,38.841597,-32.129299,-29.247671,-0.095662,8.854386
1179410,32388,2023.0,7,0.110445,0.009928,3.637767,1.072696,0.114648,-0.005109,0.018388,...,264.788010,6.589918,44.435897,0.288462,0.711538,43.638027,-38.817329,-35.851551,-0.520015,0.936654
1179411,27348,2023.0,7,0.110445,0.009928,3.124164,0.535792,0.738567,0.004386,0.020075,...,297.355611,1.198436,42.987469,0.050125,0.949875,39.977463,-46.187555,-43.382997,-1.337079,2210.000000
1179412,27136,2023.0,7,0.110445,0.009928,3.328665,1.573513,-0.025210,0.006575,0.006587,...,207.009809,-69.694545,66.440000,0.736000,0.264000,25.409579,-68.569342,-66.106647,-1.630926,48.083333
1179413,29406,2023.0,7,0.110445,0.009928,2.983618,0.517713,0.402398,0.141918,0.020642,...,244.722514,2.045230,28.666667,0.000000,1.000000,50.255279,-33.369037,-30.892654,-0.312302,14.703846

In [42]:
output = test_df[['CompNo','year','month']]
months_6 = y_pred_6['6 months']
months_12 = y_pred_12['12 months']
months_24 = y_pred_24['24 months']

In [43]:
output.to_csv('output.csv', index=False)