In [1]:
!pip install pandas google-cloud-bigquery
!pip install pandas-gbq
import pandas as pd

Requirement already satisfied: pandas in c:\documents\capstone\.venv\lib\site-packages (2.1.0)
Requirement already satisfied: google-cloud-bigquery in c:\documents\capstone\.venv\lib\site-packages (3.11.4)
Requirement already satisfied: numpy>=1.22.4 in c:\documents\capstone\.venv\lib\site-packages (from pandas) (1.25.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\documents\capstone\.venv\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\documents\capstone\.venv\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in c:\documents\capstone\.venv\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: grpcio<2.0dev,>=1.47.0 in c:\documents\capstone\.venv\lib\site-packages (from google-cloud-bigquery) (1.57.0)
Requirement already satisfied: google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5 in c:\documents\capstone\.venv\lib\site-packages (from google-cloud-bigquery) (2.11.1)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.15.0 in c:\documents\capstone\.venv\lib\site-packages (from google-cloud-bigquery) (1.22.3)
Requirement already satisfied: google-cloud-core<3.0.0dev,>=1.6.0 in c:\documents\capstone\.venv\lib\site-packages (from google-cloud-bigquery) (2.3.3)
Requirement already satisfied: google-resumable-media<3.0dev,>=0.6.0 in c:\documents\capstone\.venv\lib\site-packages (from google-cloud-bigquery) (2.5.0)
Requirement already satisfied: packaging>=20.0.0 in c:\documents\capstone\.venv\lib\site-packages (from google-cloud-bigquery) (23.1)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5 in c:\documents\capstone\.venv\lib\site-packages (from google-cloud-bigquery) (4.24.2)
Requirement already satisfied: requests<3.0.0dev,>=2.21.0 in c:\documents\capstone\.venv\lib\site-packages (from google-cloud-bigquery) (2.31.0)
Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in c:\documents\capstone\.venv\lib\site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-bigquery) (1.60.0)
Requirement already satisfied: google-auth<3.0.dev0,>=2.14.1 in c:\documents\capstone\.venv\lib\site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-bigquery) (2.22.0)
Requirement already satisfied: grpcio-status<2.0.dev0,>=1.33.2 in c:\documents\capstone\.venv\lib\site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-bigquery) (1.57.0)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in c:\documents\capstone\.venv\lib\site-packages (from google-resumable-media<3.0dev,>=0.6.0->google-cloud-bigquery) (1.5.0)
Requirement already satisfied: six>=1.5 in c:\documents\capstone\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\documents\capstone\.venv\lib\site-packages (from requests<3.0.0dev,>=2.21.0->google-cloud-bigquery) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in c:\documents\capstone\.venv\lib\site-packages (from requests<3.0.0dev,>=2.21.0->google-cloud-bigquery) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\documents\capstone\.venv\lib\site-packages (from requests<3.0.0dev,>=2.21.0->google-cloud-bigquery) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\documents\capstone\.venv\lib\site-packages (from requests<3.0.0dev,>=2.21.0->google-cloud-bigquery) (2023.7.22)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\documents\capstone\.venv\lib\site-packages (from google-auth<3.0.dev0,>=2.14.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-bigquery) (5.3.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\documents\capstone\.venv\lib\site-packages (from google-auth<3.0.dev0,>=2.14.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-bigquery) (0.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\documents\capstone\.venv\lib\site-packages (from google-auth<3.0.dev0,>=2.14.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-bigquery) (4.9)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in c:\documents\capstone\.venv\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.dev0,>=2.14.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-bigquery) (0.5.0)
Requirement already satisfied: pandas-gbq in c:\documents\capstone\.venv\lib\site-packages (0.19.2)
Requirement already satisfied: setuptools in c:\documents\capstone\.venv\lib\site-packages (from pandas-gbq) (58.1.0)
Requirement already satisfied: db-dtypes<2.0.0,>=1.0.4 in c:\documents\capstone\.venv\lib\site-packages (from pandas-gbq) (1.1.1)
Requirement already satisfied: numpy>=1.16.6 in c:\documents\capstone\.venv\lib\site-packages (from pandas-gbq) (1.25.2)
Requirement already satisfied: pandas>=1.1.4 in c:\documents\capstone\.venv\lib\site-packages (from pandas-gbq) (2.1.0)
Requirement already satisfied: pyarrow>=3.0.0 in c:\documents\capstone\.venv\lib\site-packages (from pandas-gbq) (13.0.0)
Requirement already satisfied: pydata-google-auth>=1.5.0 in c:\documents\capstone\.venv\lib\site-packages (from pandas-gbq) (1.8.2)
Requirement already satisfied: google-api-core<3.0.0dev,>=2.10.2 in c:\documents\capstone\.venv\lib\site-packages (from pandas-gbq) (2.11.1)
Requirement already satisfied: google-auth>=2.13.0 in c:\documents\capstone\.venv\lib\site-packages (from pandas-gbq) (2.22.0)
Requirement already satisfied: google-auth-oauthlib>=0.7.0 in c:\documents\capstone\.venv\lib\site-packages (from pandas-gbq) (1.0.0)
Requirement already satisfied: google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5 in c:\documents\capstone\.venv\lib\site-packages (from pandas-gbq) (3.11.4)
Requirement already satisfied: google-cloud-bigquery-storage<3.0.0dev,>=2.16.2 in c:\documents\capstone\.venv\lib\site-packages (from pandas-gbq) (2.22.0)
Requirement already satisfied: packaging>=17.0 in c:\documents\capstone\.venv\lib\site-packages (from db-dtypes<2.0.0,>=1.0.4->pandas-gbq) (23.1)
Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in c:\documents\capstone\.venv\lib\site-packages (from google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (1.60.0)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0.dev0,>=3.19.5 in c:\documents\capstone\.venv\lib\site-packages (from google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (4.24.2)
Requirement already satisfied: requests<3.0.0.dev0,>=2.18.0 in c:\documents\capstone\.venv\lib\site-packages (from google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (2.31.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\documents\capstone\.venv\lib\site-packages (from google-auth>=2.13.0->pandas-gbq) (5.3.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\documents\capstone\.venv\lib\site-packages (from google-auth>=2.13.0->pandas-gbq) (0.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\documents\capstone\.venv\lib\site-packages (from google-auth>=2.13.0->pandas-gbq) (4.9)
Requirement already satisfied: six>=1.9.0 in c:\documents\capstone\.venv\lib\site-packages (from google-auth>=2.13.0->pandas-gbq) (1.16.0)
Requirement already satisfied: urllib3<2.0 in c:\documents\capstone\.venv\lib\site-packages (from google-auth>=2.13.0->pandas-gbq) (1.26.16)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\documents\capstone\.venv\lib\site-packages (from google-auth-oauthlib>=0.7.0->pandas-gbq) (1.3.1)
Requirement already satisfied: grpcio<2.0dev,>=1.47.0 in c:\documents\capstone\.venv\lib\site-packages (from google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5->pandas-gbq) (1.57.0)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.15.0 in c:\documents\capstone\.venv\lib\site-packages (from google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5->pandas-gbq) (1.22.3)
Requirement already satisfied: google-cloud-core<3.0.0dev,>=1.6.0 in c:\documents\capstone\.venv\lib\site-packages (from google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5->pandas-gbq) (2.3.3)
Requirement already satisfied: google-resumable-media<3.0dev,>=0.6.0 in c:\documents\capstone\.venv\lib\site-packages (from google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5->pandas-gbq) (2.5.0)
Requirement already satisfied: python-dateutil<3.0dev,>=2.7.2 in c:\documents\capstone\.venv\lib\site-packages (from google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5->pandas-gbq) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\documents\capstone\.venv\lib\site-packages (from pandas>=1.1.4->pandas-gbq) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in c:\documents\capstone\.venv\lib\site-packages (from pandas>=1.1.4->pandas-gbq) (2023.3)
Requirement already satisfied: grpcio-status<2.0.dev0,>=1.33.2 in c:\documents\capstone\.venv\lib\site-packages (from google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (1.57.0)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in c:\documents\capstone\.venv\lib\site-packages (from google-resumable-media<3.0dev,>=0.6.0->google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5->pandas-gbq) (1.5.0)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in c:\documents\capstone\.venv\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth>=2.13.0->pandas-gbq) (0.5.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\documents\capstone\.venv\lib\site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in c:\documents\capstone\.venv\lib\site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\documents\capstone\.venv\lib\site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (2023.7.22)
Requirement already satisfied: oauthlib>=3.0.0 in c:\documents\capstone\.venv\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.7.0->pandas-gbq) (3.2.2)

In [2]:
pip install pandas-gbq

Requirement already satisfied: pandas-gbq in c:\documents\capstone\.venv\lib\site-packages (0.19.2)
Requirement already satisfied: setuptools in c:\documents\capstone\.venv\lib\site-packages (from pandas-gbq) (58.1.0)
Requirement already satisfied: db-dtypes<2.0.0,>=1.0.4 in c:\documents\capstone\.venv\lib\site-packages (from pandas-gbq) (1.1.1)
Requirement already satisfied: numpy>=1.16.6 in c:\documents\capstone\.venv\lib\site-packages (from pandas-gbq) (1.25.2)
Requirement already satisfied: pandas>=1.1.4 in c:\documents\capstone\.venv\lib\site-packages (from pandas-gbq) (2.1.0)
Requirement already satisfied: pyarrow>=3.0.0 in c:\documents\capstone\.venv\lib\site-packages (from pandas-gbq) (13.0.0)
Requirement already satisfied: pydata-google-auth>=1.5.0 in c:\documents\capstone\.venv\lib\site-packages (from pandas-gbq) (1.8.2)
Requirement already satisfied: google-api-core<3.0.0dev,>=2.10.2 in c:\documents\capstone\.venv\lib\site-packages (from pandas-gbq) (2.11.1)
Requirement already satisfied: google-auth>=2.13.0 in c:\documents\capstone\.venv\lib\site-packages (from pandas-gbq) (2.22.0)
Requirement already satisfied: google-auth-oauthlib>=0.7.0 in c:\documents\capstone\.venv\lib\site-packages (from pandas-gbq) (1.0.0)
Requirement already satisfied: google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5 in c:\documents\capstone\.venv\lib\site-packages (from pandas-gbq) (3.11.4)
Requirement already satisfied: google-cloud-bigquery-storage<3.0.0dev,>=2.16.2 in c:\documents\capstone\.venv\lib\site-packages (from pandas-gbq) (2.22.0)
Requirement already satisfied: packaging>=17.0 in c:\documents\capstone\.venv\lib\site-packages (from db-dtypes<2.0.0,>=1.0.4->pandas-gbq) (23.1)
Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in c:\documents\capstone\.venv\lib\site-packages (from google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (1.60.0)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0.dev0,>=3.19.5 in c:\documents\capstone\.venv\lib\site-packages (from google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (4.24.2)
Requirement already satisfied: requests<3.0.0.dev0,>=2.18.0 in c:\documents\capstone\.venv\lib\site-packages (from google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (2.31.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\documents\capstone\.venv\lib\site-packages (from google-auth>=2.13.0->pandas-gbq) (5.3.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\documents\capstone\.venv\lib\site-packages (from google-auth>=2.13.0->pandas-gbq) (0.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\documents\capstone\.venv\lib\site-packages (from google-auth>=2.13.0->pandas-gbq) (4.9)
Requirement already satisfied: six>=1.9.0 in c:\documents\capstone\.venv\lib\site-packages (from google-auth>=2.13.0->pandas-gbq) (1.16.0)
Requirement already satisfied: urllib3<2.0 in c:\documents\capstone\.venv\lib\site-packages (from google-auth>=2.13.0->pandas-gbq) (1.26.16)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\documents\capstone\.venv\lib\site-packages (from google-auth-oauthlib>=0.7.0->pandas-gbq) (1.3.1)
Requirement already satisfied: grpcio<2.0dev,>=1.47.0 in c:\documents\capstone\.venv\lib\site-packages (from google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5->pandas-gbq) (1.57.0)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.15.0 in c:\documents\capstone\.venv\lib\site-packages (from google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5->pandas-gbq) (1.22.3)
Requirement already satisfied: google-cloud-core<3.0.0dev,>=1.6.0 in c:\documents\capstone\.venv\lib\site-packages (from google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5->pandas-gbq) (2.3.3)
Requirement already satisfied: google-resumable-media<3.0dev,>=0.6.0 in c:\documents\capstone\.venv\lib\site-packages (from google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5->pandas-gbq) (2.5.0)
Requirement already satisfied: python-dateutil<3.0dev,>=2.7.2 in c:\documents\capstone\.venv\lib\site-packages (from google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5->pandas-gbq) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\documents\capstone\.venv\lib\site-packages (from pandas>=1.1.4->pandas-gbq) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in c:\documents\capstone\.venv\lib\site-packages (from pandas>=1.1.4->pandas-gbq) (2023.3)
Requirement already satisfied: grpcio-status<2.0.dev0,>=1.33.2 in c:\documents\capstone\.venv\lib\site-packages (from google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (1.57.0)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in c:\documents\capstone\.venv\lib\site-packages (from google-resumable-media<3.0dev,>=0.6.0->google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5->pandas-gbq) (1.5.0)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in c:\documents\capstone\.venv\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth>=2.13.0->pandas-gbq) (0.5.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\documents\capstone\.venv\lib\site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in c:\documents\capstone\.venv\lib\site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\documents\capstone\.venv\lib\site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (2023.7.22)
Requirement already satisfied: oauthlib>=3.0.0 in c:\documents\capstone\.venv\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.7.0->pandas-gbq) (3.2.2)
Note: you may need to restart the kernel to use updated packages.

In [4]:
from google.oauth2 import service_account
import pandas as pd
import pandas_gbq as gbq
credentials_path = '../token.json'

# Authenticate with your credentials
credentials = service_account.Credentials.from_service_account_file(
    credentials_path, scopes=['https://www.googleapis.com/auth/bigquery'])

# Set the credentials for pandas_gbq
gbq.context.credentials = credentials

In [5]:
project_id = 'capstone-398012'
dataset_id = 'capstone'
table_id = "X_Y_merged"

In [6]:
from pandas_gbq import read_gbq

query = f"""
SELECT *
FROM `{project_id}.{dataset_id}.{table_id}`

"""

# Authenticate and read data from BigQuery into a DataFrame
df = read_gbq(query, project_id=project_id, dialect='standard')
df

c:\Documents\Capstone\.venv\lib\site-packages\google\cloud\bigquery\table.py:2155: UserWarning: A progress bar was requested, but there was an error loading the tqdm library. Please install tqdm to use the progress bar functionality.
  record_batch = self.to_arrow(

,CompNo,yyyy,mm,StkIndx,STInt,dtdlevel,dtdtrend,liqnonfinlevel,liqnonfintrend,ni2talevel,...,sigma,liqfinlevel,lqfintrend,DTDmedianFin,DTDmedianNonFin,dummy297fin,EventDate,Event_type,Sector_Number,Exchange
0,26990,2023,7,0.110445,0.009928,4.874043,0.537756,0.000000,0.000000e+00,0.003009,...,0.049103,-3.418569,-0.149087,2.596495,0.000000,1,202307,0,14.0,15
1,27005,2023,7,0.110445,0.009928,6.375460,-0.447124,0.000000,0.000000e+00,0.003226,...,0.065213,-1.643673,0.291813,2.596495,0.000000,1,202307,0,15.0,15
2,27030,2023,7,0.110445,0.009928,3.875769,0.519613,0.000000,0.000000e+00,0.002722,...,0.060196,-1.765111,0.115349,2.596495,0.000000,1,202307,0,14.0,15
3,27035,2023,7,0.110445,0.009928,2.130511,0.361442,0.000000,0.000000e+00,0.000949,...,0.064415,-3.602947,0.037359,2.596495,0.000000,1,202307,0,14.0,15
4,27037,2023,7,0.110445,0.009928,5.436649,-3.216218,0.000000,0.000000e+00,-0.002387,...,0.170656,-0.816766,0.010185,2.596495,0.000000,1,202307,0,14.0,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8617,211542,2023,7,0.015960,-0.010290,NaN,NaN,1.595832,-2.220446e-16,-0.094074,...,NaN,0.000000,0.000000,0.000000,2.087496,0,202307,0,18.0,16
8618,211546,2023,7,0.015960,-0.010290,7.349152,-0.538347,2.291604,0.000000e+00,-0.088621,...,0.225663,0.000000,0.000000,0.000000,2.087496,0,202307,0,19.0,16
8619,211564,2023,7,0.015960,-0.010290,0.972123,0.000000,4.787727,0.000000e+00,-0.055728,...,NaN,0.000000,0.000000,0.000000,2.087496,0,202307,0,18.0,16
8620,211664,2023,7,0.015960,-0.010290,4.090032,0.000000,1.198122,0.000000e+00,-0.074286,...,0.333307,0.000000,0.000000,0.000000,2.087496,0,202307,0,18.0,16
8621,211787,2023,7,0.015960,-0.010290,NaN,NaN,2.318369,0.000000e+00,-0.048236,...,NaN,0.000000,0.000000,0.000000,2.087496,0,202307,0,18.0,16

In [7]:
df.isna().sum().sort_values(ascending=False)

dtdlevel           2297
dtdtrend           2297
m2b                2229
sigma              2144
ni2talevel         2135
ni2tatrend         2135
liqnonfinlevel     1737
liqnonfintrend     1737
lqfintrend          431
liqfinlevel         431
sizelevel           156
sizetrend           156
Sector_Number       114
DTDmedianNonFin       2
DTDmedianFin          1
dummy297fin           0
EventDate             0
Event_type            0
CompNo                0
yyyy                  0
STInt                 0
StkIndx               0
mm                    0
Exchange              0
dtype: int64

In [8]:
new_df = df
new_df

,CompNo,yyyy,mm,StkIndx,STInt,dtdlevel,dtdtrend,liqnonfinlevel,liqnonfintrend,ni2talevel,...,sigma,liqfinlevel,lqfintrend,DTDmedianFin,DTDmedianNonFin,dummy297fin,EventDate,Event_type,Sector_Number,Exchange
0,26990,2023,7,0.110445,0.009928,4.874043,0.537756,0.000000,0.000000e+00,0.003009,...,0.049103,-3.418569,-0.149087,2.596495,0.000000,1,202307,0,14.0,15
1,27005,2023,7,0.110445,0.009928,6.375460,-0.447124,0.000000,0.000000e+00,0.003226,...,0.065213,-1.643673,0.291813,2.596495,0.000000,1,202307,0,15.0,15
2,27030,2023,7,0.110445,0.009928,3.875769,0.519613,0.000000,0.000000e+00,0.002722,...,0.060196,-1.765111,0.115349,2.596495,0.000000,1,202307,0,14.0,15
3,27035,2023,7,0.110445,0.009928,2.130511,0.361442,0.000000,0.000000e+00,0.000949,...,0.064415,-3.602947,0.037359,2.596495,0.000000,1,202307,0,14.0,15
4,27037,2023,7,0.110445,0.009928,5.436649,-3.216218,0.000000,0.000000e+00,-0.002387,...,0.170656,-0.816766,0.010185,2.596495,0.000000,1,202307,0,14.0,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8617,211542,2023,7,0.015960,-0.010290,NaN,NaN,1.595832,-2.220446e-16,-0.094074,...,NaN,0.000000,0.000000,0.000000,2.087496,0,202307,0,18.0,16
8618,211546,2023,7,0.015960,-0.010290,7.349152,-0.538347,2.291604,0.000000e+00,-0.088621,...,0.225663,0.000000,0.000000,0.000000,2.087496,0,202307,0,19.0,16
8619,211564,2023,7,0.015960,-0.010290,0.972123,0.000000,4.787727,0.000000e+00,-0.055728,...,NaN,0.000000,0.000000,0.000000,2.087496,0,202307,0,18.0,16
8620,211664,2023,7,0.015960,-0.010290,4.090032,0.000000,1.198122,0.000000e+00,-0.074286,...,0.333307,0.000000,0.000000,0.000000,2.087496,0,202307,0,18.0,16
8621,211787,2023,7,0.015960,-0.010290,NaN,NaN,2.318369,0.000000e+00,-0.048236,...,NaN,0.000000,0.000000,0.000000,2.087496,0,202307,0,18.0,16

In [9]:
nan_count = new_df.isna().sum(axis=1)

# Create a new column with the NaN count
new_df['nan_count'] = nan_count
new_df

,CompNo,yyyy,mm,StkIndx,STInt,dtdlevel,dtdtrend,liqnonfinlevel,liqnonfintrend,ni2talevel,...,liqfinlevel,lqfintrend,DTDmedianFin,DTDmedianNonFin,dummy297fin,EventDate,Event_type,Sector_Number,Exchange,nan_count
0,26990,2023,7,0.110445,0.009928,4.874043,0.537756,0.000000,0.000000e+00,0.003009,...,-3.418569,-0.149087,2.596495,0.000000,1,202307,0,14.0,15,0
1,27005,2023,7,0.110445,0.009928,6.375460,-0.447124,0.000000,0.000000e+00,0.003226,...,-1.643673,0.291813,2.596495,0.000000,1,202307,0,15.0,15,0
2,27030,2023,7,0.110445,0.009928,3.875769,0.519613,0.000000,0.000000e+00,0.002722,...,-1.765111,0.115349,2.596495,0.000000,1,202307,0,14.0,15,0
3,27035,2023,7,0.110445,0.009928,2.130511,0.361442,0.000000,0.000000e+00,0.000949,...,-3.602947,0.037359,2.596495,0.000000,1,202307,0,14.0,15,0
4,27037,2023,7,0.110445,0.009928,5.436649,-3.216218,0.000000,0.000000e+00,-0.002387,...,-0.816766,0.010185,2.596495,0.000000,1,202307,0,14.0,15,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8617,211542,2023,7,0.015960,-0.010290,NaN,NaN,1.595832,-2.220446e-16,-0.094074,...,0.000000,0.000000,0.000000,2.087496,0,202307,0,18.0,16,3
8618,211546,2023,7,0.015960,-0.010290,7.349152,-0.538347,2.291604,0.000000e+00,-0.088621,...,0.000000,0.000000,0.000000,2.087496,0,202307,0,19.0,16,0
8619,211564,2023,7,0.015960,-0.010290,0.972123,0.000000,4.787727,0.000000e+00,-0.055728,...,0.000000,0.000000,0.000000,2.087496,0,202307,0,18.0,16,1
8620,211664,2023,7,0.015960,-0.010290,4.090032,0.000000,1.198122,0.000000e+00,-0.074286,...,0.000000,0.000000,0.000000,2.087496,0,202307,0,18.0,16,0
8621,211787,2023,7,0.015960,-0.010290,NaN,NaN,2.318369,0.000000e+00,-0.048236,...,0.000000,0.000000,0.000000,2.087496,0,202307,0,18.0,16,6

In [10]:
for i in range(22):
    print(str(i) + ":")
    print(len(new_df[new_df['nan_count']>i]))

0:
2568
1:
2393
2:
2316
3:
2202
4:
2185
5:
2164
6:
2119
7:
1924
8:
73
9:
58
10:
0
11:
0
12:
0
13:
0
14:
0
15:
0
16:
0
17:
0
18:
0
19:
0
20:
0
21:
0

In [11]:
#drop all rows with nan_count >= 5

new_df.drop(new_df[new_df['nan_count'] >= 5].index, inplace=True)
new_df

,CompNo,yyyy,mm,StkIndx,STInt,dtdlevel,dtdtrend,liqnonfinlevel,liqnonfintrend,ni2talevel,...,liqfinlevel,lqfintrend,DTDmedianFin,DTDmedianNonFin,dummy297fin,EventDate,Event_type,Sector_Number,Exchange,nan_count
0,26990,2023,7,0.110445,0.009928,4.874043,0.537756,0.000000,0.000000e+00,0.003009,...,-3.418569,-0.149087,2.596495,0.000000,1,202307,0,14.0,15,0
1,27005,2023,7,0.110445,0.009928,6.375460,-0.447124,0.000000,0.000000e+00,0.003226,...,-1.643673,0.291813,2.596495,0.000000,1,202307,0,15.0,15,0
2,27030,2023,7,0.110445,0.009928,3.875769,0.519613,0.000000,0.000000e+00,0.002722,...,-1.765111,0.115349,2.596495,0.000000,1,202307,0,14.0,15,0
3,27035,2023,7,0.110445,0.009928,2.130511,0.361442,0.000000,0.000000e+00,0.000949,...,-3.602947,0.037359,2.596495,0.000000,1,202307,0,14.0,15,0
4,27037,2023,7,0.110445,0.009928,5.436649,-3.216218,0.000000,0.000000e+00,-0.002387,...,-0.816766,0.010185,2.596495,0.000000,1,202307,0,14.0,15,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8616,211494,2023,7,0.015960,-0.010290,13.575741,0.258830,2.108105,0.000000e+00,-0.003608,...,0.000000,0.000000,0.000000,2.087496,0,202307,0,18.0,16,0
8617,211542,2023,7,0.015960,-0.010290,NaN,NaN,1.595832,-2.220446e-16,-0.094074,...,0.000000,0.000000,0.000000,2.087496,0,202307,0,18.0,16,3
8618,211546,2023,7,0.015960,-0.010290,7.349152,-0.538347,2.291604,0.000000e+00,-0.088621,...,0.000000,0.000000,0.000000,2.087496,0,202307,0,19.0,16,0
8619,211564,2023,7,0.015960,-0.010290,0.972123,0.000000,4.787727,0.000000e+00,-0.055728,...,0.000000,0.000000,0.000000,2.087496,0,202307,0,18.0,16,1
8620,211664,2023,7,0.015960,-0.010290,4.090032,0.000000,1.198122,0.000000e+00,-0.074286,...,0.000000,0.000000,0.000000,2.087496,0,202307,0,18.0,16,0

In [12]:
new_df.isna().sum().sort_values(ascending=False)

sigma              191
dtdlevel           128
dtdtrend           128
Sector_Number       91
sizetrend           45
sizelevel           45
m2b                 45
liqnonfinlevel      22
liqnonfintrend      22
lqfintrend          10
liqfinlevel         10
ni2talevel           1
ni2tatrend           1
EventDate            0
DTDmedianNonFin      0
Event_type           0
Exchange             0
dummy297fin          0
CompNo               0
DTDmedianFin         0
yyyy                 0
STInt                0
StkIndx              0
mm                   0
nan_count            0
dtype: int64

In [13]:
#list of columns that contain NA 
na_cols = ['liqnonfinlevel', 'liqnonfintrend', 'dtdlevel', 'dtdtrend', 'DTDmedianNonFin', 'Sector_Number', 'DTDmedianFin', 'sigma', 'StkIndx']

#create new columns (_notNA) for each column that contains na values where 1 if original column is not na and 0 otherwise
for col in na_cols:
    new_col = col + '_notNA'
    new_df[new_col] = new_df[col].notna().astype(int)

new_df

,CompNo,yyyy,mm,StkIndx,STInt,dtdlevel,dtdtrend,liqnonfinlevel,liqnonfintrend,ni2talevel,...,nan_count,liqnonfinlevel_notNA,liqnonfintrend_notNA,dtdlevel_notNA,dtdtrend_notNA,DTDmedianNonFin_notNA,Sector_Number_notNA,DTDmedianFin_notNA,sigma_notNA,StkIndx_notNA
0,26990,2023,7,0.110445,0.009928,4.874043,0.537756,0.000000,0.000000e+00,0.003009,...,0,1,1,1,1,1,1,1,1,1
1,27005,2023,7,0.110445,0.009928,6.375460,-0.447124,0.000000,0.000000e+00,0.003226,...,0,1,1,1,1,1,1,1,1,1
2,27030,2023,7,0.110445,0.009928,3.875769,0.519613,0.000000,0.000000e+00,0.002722,...,0,1,1,1,1,1,1,1,1,1
3,27035,2023,7,0.110445,0.009928,2.130511,0.361442,0.000000,0.000000e+00,0.000949,...,0,1,1,1,1,1,1,1,1,1
4,27037,2023,7,0.110445,0.009928,5.436649,-3.216218,0.000000,0.000000e+00,-0.002387,...,0,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8616,211494,2023,7,0.015960,-0.010290,13.575741,0.258830,2.108105,0.000000e+00,-0.003608,...,0,1,1,1,1,1,1,1,1,1
8617,211542,2023,7,0.015960,-0.010290,NaN,NaN,1.595832,-2.220446e-16,-0.094074,...,3,1,1,0,0,1,1,1,0,1
8618,211546,2023,7,0.015960,-0.010290,7.349152,-0.538347,2.291604,0.000000e+00,-0.088621,...,0,1,1,1,1,1,1,1,1,1
8619,211564,2023,7,0.015960,-0.010290,0.972123,0.000000,4.787727,0.000000e+00,-0.055728,...,1,1,1,1,1,1,1,1,0,1
8620,211664,2023,7,0.015960,-0.010290,4.090032,0.000000,1.198122,0.000000e+00,-0.074286,...,0,1,1,1,1,1,1,1,1,1

In [14]:
new_df.shape

(6437, 34)

In [15]:
grouped_df = new_df.groupby('CompNo')
grouped_df[na_cols].mean()

,liqnonfinlevel,liqnonfintrend,dtdlevel,dtdtrend,DTDmedianNonFin,Sector_Number,DTDmedianFin,sigma,StkIndx
CompNo,,,,,,,,,
18729,0.401776,-0.213851,0.857282,-0.050431,3.244875,17.0,0.0,0.176984,0.110445
22043,1.561046,-0.163734,0.415476,-0.342681,3.244875,16.0,0.0,0.502508,0.110445
26978,1.135380,0.003565,5.726758,0.733746,3.244875,17.0,0.0,0.069988,0.110445
26979,0.566073,-0.048648,9.589458,1.250903,3.244875,16.0,0.0,0.051762,0.110445
26983,0.853522,0.013882,5.106642,1.046824,3.244875,19.0,0.0,0.113753,0.110445
...,...,...,...,...,...,...,...,...,...
211607,1.015179,-0.068393,8.511873,-0.123346,3.244875,17.0,0.0,0.086997,0.110445
211664,1.198122,0.000000,4.090032,0.000000,2.087496,18.0,0.0,0.333307,0.015960
211730,0.676789,0.000000,2.093328,0.000000,3.244875,13.0,0.0,0.410035,0.110445
211752,2.791912,0.000000,NaN,NaN,3.244875,18.0,0.0,0.268586,0.110445
211801,0.897990,0.000000,NaN,NaN,3.244875,13.0,0.0,0.183675,0.110445

In [16]:
mean_values = grouped_df[na_cols].transform('mean')

new_df[na_cols] = new_df[na_cols].fillna(mean_values)

new_df

,CompNo,yyyy,mm,StkIndx,STInt,dtdlevel,dtdtrend,liqnonfinlevel,liqnonfintrend,ni2talevel,...,nan_count,liqnonfinlevel_notNA,liqnonfintrend_notNA,dtdlevel_notNA,dtdtrend_notNA,DTDmedianNonFin_notNA,Sector_Number_notNA,DTDmedianFin_notNA,sigma_notNA,StkIndx_notNA
0,26990,2023,7,0.110445,0.009928,4.874043,0.537756,0.000000,0.000000e+00,0.003009,...,0,1,1,1,1,1,1,1,1,1
1,27005,2023,7,0.110445,0.009928,6.375460,-0.447124,0.000000,0.000000e+00,0.003226,...,0,1,1,1,1,1,1,1,1,1
2,27030,2023,7,0.110445,0.009928,3.875769,0.519613,0.000000,0.000000e+00,0.002722,...,0,1,1,1,1,1,1,1,1,1
3,27035,2023,7,0.110445,0.009928,2.130511,0.361442,0.000000,0.000000e+00,0.000949,...,0,1,1,1,1,1,1,1,1,1
4,27037,2023,7,0.110445,0.009928,5.436649,-3.216218,0.000000,0.000000e+00,-0.002387,...,0,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8616,211494,2023,7,0.015960,-0.010290,13.575741,0.258830,2.108105,0.000000e+00,-0.003608,...,0,1,1,1,1,1,1,1,1,1
8617,211542,2023,7,0.015960,-0.010290,NaN,NaN,1.595832,-2.220446e-16,-0.094074,...,3,1,1,0,0,1,1,1,0,1
8618,211546,2023,7,0.015960,-0.010290,7.349152,-0.538347,2.291604,0.000000e+00,-0.088621,...,0,1,1,1,1,1,1,1,1,1
8619,211564,2023,7,0.015960,-0.010290,0.972123,0.000000,4.787727,0.000000e+00,-0.055728,...,1,1,1,1,1,1,1,1,0,1
8620,211664,2023,7,0.015960,-0.010290,4.090032,0.000000,1.198122,0.000000e+00,-0.074286,...,0,1,1,1,1,1,1,1,1,1

In [18]:
print(new_df[new_df.isna().any(axis=1)])

      CompNo  yyyy mm   StkIndx     STInt    dtdlevel   dtdtrend  \
127    30643  2023  7  0.110445  0.009928         NaN        NaN
290    36114  2023  7  0.110445  0.009928   16.785337   9.127457
448    44088  2023  7  0.110445  0.009928         NaN        NaN
600   131867  2023  7  0.110445  0.009928    0.675758  -0.475205
886   205354  2023  7  0.110445  0.009928  103.738407 -35.341088
...      ...   ... ..       ...       ...         ...        ...
8610  211421  2023  7  0.015960 -0.010290         NaN        NaN
8611  211423  2023  7  0.015960 -0.010290   12.160022   0.000000
8613  211434  2023  7  0.015960 -0.010290         NaN        NaN
8617  211542  2023  7  0.015960 -0.010290         NaN        NaN
8619  211564  2023  7  0.015960 -0.010290    0.972123   0.000000

      liqnonfinlevel  liqnonfintrend  ni2talevel  ...  nan_count  \
127         0.000000    0.000000e+00   -0.000004  ...          2
290         0.000000    0.000000e+00    0.011002  ...          2
448         0.000000    0.000000e+00   -0.000651  ...          2
600         0.000000    0.000000e+00   -0.101552  ...          2
886         0.000000    0.000000e+00    0.000951  ...          2
...              ...             ...         ...  ...        ...
8610        0.848237    0.000000e+00   -0.040258  ...          3
8611        3.903415    4.440892e-16   -0.043879  ...          1
8613        1.103168    0.000000e+00   -0.104520  ...          3
8617        1.595832   -2.220446e-16   -0.094074  ...          3
8619        4.787727    0.000000e+00   -0.055728  ...          1

      liqnonfinlevel_notNA  liqnonfintrend_notNA  dtdlevel_notNA  \
127                      1                     1               0
290                      1                     1               1
448                      1                     1               0
600                      1                     1               1
886                      1                     1               1
...                    ...                   ...             ...
8610                     1                     1               0
8611                     1                     1               1
8613                     1                     1               0
8617                     1                     1               0
8619                     1                     1               1

      dtdtrend_notNA  DTDmedianNonFin_notNA  Sector_Number_notNA  \
127                0                      1                    1
290                1                      1                    1
448                0                      1                    1
600                1                      1                    1
886                1                      1                    1
...              ...                    ...                  ...
8610               0                      1                    1
8611               1                      1                    1
8613               0                      1                    1
8617               0                      1                    1
8619               1                      1                    1

      DTDmedianFin_notNA  sigma_notNA  StkIndx_notNA
127                    1            1              1
290                    1            1              1
448                    1            1              1
600                    1            1              1
886                    1            1              1
...                  ...          ...            ...
8610                   1            0              1
8611                   1            0              1
8613                   1            0              1
8617                   1            0              1
8619                   1            0              1

[383 rows x 34 columns]

In [19]:
new_df.isna().sum().sort_values(ascending=False)

sigma                    191
dtdtrend                 128
dtdlevel                 128
Sector_Number             91
m2b                       45
sizetrend                 45
sizelevel                 45
liqnonfinlevel            22
liqnonfintrend            22
liqfinlevel               10
lqfintrend                10
ni2talevel                 1
ni2tatrend                 1
nan_count                  0
Sector_Number_notNA        0
DTDmedianFin_notNA         0
sigma_notNA                0
DTDmedianNonFin_notNA      0
dtdtrend_notNA             0
dtdlevel_notNA             0
liqnonfintrend_notNA       0
liqnonfinlevel_notNA       0
CompNo                     0
DTDmedianFin               0
Exchange                   0
Event_type                 0
EventDate                  0
dummy297fin                0
DTDmedianNonFin            0
yyyy                       0
STInt                      0
StkIndx                    0
mm                         0
StkIndx_notNA              0
dtype: int64

In [20]:
new_df.to_gbq(destination_table=f'{project_id}.{dataset_id}.filled_table', project_id=project_id, if_exists='replace')