In [1]:
import pandas as pd
from google.oauth2 import service_account
import pandas_gbq as gbq

In [2]:
credentials_path = 'token.json'

# Authenticate with your credentials
credentials = service_account.Credentials.from_service_account_file(
    credentials_path, scopes=['https://www.googleapis.com/auth/bigquery'])

# Set the credentials for pandas_gbq
gbq.context.credentials = credentials

project_id = 'capstone-398012'
dataset_id = 'capstone'
table_id = "comp_na_daily_all"

In [21]:
df = pd.read_csv('comp_na_daily_all.csv')
df = df.astype(str)

C:\Users\Melissa\AppData\Local\Temp\ipykernel_13016\570074204.py:1: DtypeWarning: Columns (10,12,13,17,18,20,25,26,30,32,33,34,35,647,648,654,668,669,674,679) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('comp_na_daily_all.csv')

In [22]:
df.head()

,gvkey,datadate,fyearq,fqtr,fyr,indfmt,consol,popsrc,datafmt,tic,...,priusa,sic,spcindcd,spcseccd,spcsrc,state,stko,weburl,dldte,ipodate
0,1004,2/29/2000,1999,3.0,5,INDL,C,D,STD,AIR,...,1.0,5080.0,110.0,925.0,B,IL,0.0,www.aarcorp.com,nan,1/1/1988
1,1004,5/31/2000,1999,4.0,5,INDL,C,D,STD,AIR,...,1.0,5080.0,110.0,925.0,B,IL,0.0,www.aarcorp.com,nan,1/1/1988
2,1004,8/31/2000,2000,1.0,5,INDL,C,D,STD,AIR,...,1.0,5080.0,110.0,925.0,B,IL,0.0,www.aarcorp.com,nan,1/1/1988
3,1004,11/30/2000,2000,2.0,5,INDL,C,D,STD,AIR,...,1.0,5080.0,110.0,925.0,B,IL,0.0,www.aarcorp.com,nan,1/1/1988
4,1004,2/28/2001,2000,3.0,5,INDL,C,D,STD,AIR,...,1.0,5080.0,110.0,925.0,B,IL,0.0,www.aarcorp.com,nan,1/1/1988

In [24]:
df.to_gbq(destination_table=f'{project_id}.{dataset_id}.compna_table', project_id=project_id, if_exists='replace')

100%|██████████| 1/1 [00:00<00:00, 952.60it/s]